### ISSUE TITLE
Creating a project logo

### ISSUE THREAD

**Issue by ctron** [eclipse/packages#1]
We need a project logo.

**Comment by eeeveee1** [comment]
Here are three proposals.
These are not final art works, it's possible to refine it.
Let me know what you think.

![EiotP_Logo600_20191014](https://user-images.githubusercontent.com/56560642/66775924-71662b80-eec5-11e9-8bac-62e6cb01897a.png)

**Comment by thjaeckle** [comment]
Great start of the project, Jens. Kudos for setting up such a good website so quickly.
A logo would indeed be important to have a visual.

Thanks for your suggestions, @eeeveee1.
I like 3 because of the package :wink:
I like 2 because of the mosaic idea, several smaller pieces of the same color forming a bigger piece.
From my limited experience in logo design I would not suggest making a logo containing more packages as the details would get too small.
But maybe a good old rubik cube?

**Comment by ctron** [comment]
My favorite is #1 … It is colorful, if you look close enough it is three triangles combined to something bigger, is resembles the "play" button, combined with the text it is an arrow, pointing you into the right direction, and I think you can have smaller, down to tiny versions of that as well. And just imagine seeing this in  long list of other logos, it will stick out.

**Comment by dejanb** [comment]
#1 I think will work the best in different sizes ... from icon to the bigger prints 

#2 I like this one the most visually

**Comment by jbtrystram** [comment]
My favorite one is also the first. The shape and colors are more appealing to me. 
#2 is nice as well, but would  benefit from bigger inner shapes and more bright colors :)

**Comment by calohmn** [comment]
In terms of how logo and the text are structured, I like #1 the best. It's the most compact and the eye doesn't have to wander much to get the text and logo (and "IoT" is in the center, emphasizing that).
In terms of logo itself, I also like #1, with #3 being second.

**Comment by dguggemos** [comment]
I like #3 most, because it comes closest to my idea of a package. Maybe we could make it a bit more colorful? #2 is also good, but could be difficult as a small icon. I don't like #1 because I think it has too many colors and is somehow irritating to the eyes (at least my eyes :wink:).

**Comment by stmaute** [comment]
I also like #3 the most. For me it looks like the closest to a package. My second favourite would be #2.  
I personally don't like to colorful logos like #1 but this is my own opinion.

**Comment by eeeveee1** [comment]
Thank you all for your constructive response.
I did some changes to #1 and #3, as both got 4 votes.
You can also see how the logos work in small icons.

Pls tell me your opinion abt it!

![EiotP_Logo_640px_20191016](https://user-images.githubusercontent.com/56560642/66912549-117d9b00-f013-11e9-8c60-52384cccda99.png)

**Comment by stmaute** [comment]
I like #4 the most. The others are a bit to colorful for me.

**Comment by ctron** [comment]
I prefer #2:
* It renders well in small sizes
* Colors are less bright than in the previous iteration
* But most important, it will stick out, and people will recognize it, compared to the less vibrant colors of the others.

**Comment by calohmn** [comment]
I vote for #2. Pleasant color combination.

**Comment by thjaeckle** [comment]
2 reminds me too much of the Google Play store.
4 does indeed not render well in small sizes, but still my favorite.

**Comment by ctron** [comment]
It looks like that we have +3 for (2) and +2 for (4) … plus the fact that we would have issues in smaller sizes when going with (4).

So let's take (2) then and move on. I will go ahead and ask EMO for approval as well. As I don't anticipate any problems there, I would suggest to already continue with the logo in the meantime.

Thanks everyone for the feedback!
