### ISSUE TITLE
questions on Installation

### ISSUE THREAD

**Issue by BaerSy** [eclipse/packages#105]
I  followed the instructions to install the IOT package, and got below pods running.  Just want to know whether "Hawkbit " has been installed yet?  I can't see it in the list...

NAME                                      READY   STATUS    RESTARTS   AGE
c2e-adapter-amqp-vertx-5b9f686b78-ml26x   1/1     Running   1          57m
c2e-adapter-http-vertx-5886b78898-bw7kb   1/1     Running   1          56m
c2e-adapter-mqtt-vertx-656cf5df-7nckp     1/1     Running   1          57m
c2e-artemis-74566bc785-xpq4m              1/1     Running   3          57m
c2e-dispatch-router-85697cfc8b-7vnqb      1/1     Running   0          57m
c2e-ditto-concierge-b87c8f664-tw46q       1/1     Running   0          57m
c2e-ditto-connectivity-865f674645-fvsg6   1/1     Running   0          56m
c2e-ditto-gateway-845b7dcd4-ljfrm         1/1     Running   0          57m
c2e-ditto-nginx-86bbcc769d-xd9tc          1/1     Running   0          57m
c2e-ditto-policies-c475d448d-jq8br        1/1     Running   0          57m
c2e-ditto-swaggerui-65f496dcfc-br7rm      1/1     Running   0          57m
c2e-ditto-things-5c4d6dd558-bn68g         1/1     Running   0          56m
c2e-ditto-thingssearch-59b497474-6ksnz    1/1     Running   0          57m
c2e-service-auth-588ddc4bb-kdn6r          1/1     Running   1          56m
c2e-service-device-registry-0             1/1     Running   1          57m
ditto-mongodb-6775f789b9-qgk7v            1/1     Running   0          57m

**Comment by ctron** [comment]
No unfortunately Hawkbit isn't part of that yet.
