### ISSUE TITLE
Load Balancing issue

### ISSUE THREAD

**Issue by roullli** [eclipse/packages#110]
Hi,
Is there any documentation regarding installing a load balancer locally for my private Kubernetes?
Thanks in advance.

**Comment by ctron** [comment]
Hello @roullli … when using Minikube, you should be able to follow the following instructions: https://minikube.sigs.k8s.io/docs/handbook/accessing/#loadbalancer-access

**Comment by sophokles73** [comment]
@roullli Did you find the information required to solve your issue? Can this be closed?

**Comment by roullli** [comment]
Yes, thank you. I used MetalLB to deal with this issue. 
I'll close this issue.
