### ISSUE TITLE
Hono's adapter can't be ready.

### ISSUE THREAD

**Issue by Geonjae-Joo** [eclipse/packages#139]
Few days ago, hono adapters suddenly stopped working.
I updated repo, and still won't work.

can anyone tell me how to fix it?
![1](https://user-images.githubusercontent.com/62494715/93728659-cfce7a80-fbfb-11ea-9d13-bb41c6020dae.png)

![image](https://user-images.githubusercontent.com/62494715/93728691-f42a5700-fbfb-11ea-953a-99474d17a03f.png)

![image](https://user-images.githubusercontent.com/62494715/93728782-7155cc00-fbfc-11ea-93d8-a55d8faf94c6.png)

**Comment by calohmn** [comment]
This is a duplicate of #136: The Hono demo certificates have expired. The Hono chart had already been updated. The cloud2Edge chart has just been updated as well (version 0.1.1) to reference the updated Hono chart version.

**Comment by Geonjae-Joo** [comment]
@calohmn  Thank you so much!
