### ISSUE TITLE
Error creating cloud2edge demo device in Hono

### ISSUE THREAD

**Issue by calohmn** [eclipse/packages#142]
As reported in the Hono Gitter channel:
When using the cloud2edge package (chart version > 0.0.10), creating the device with the identifier "org.eclipse.packages.c2e:device" (containing a colon, as required by Ditto) fails with the error:
````
failed validation: value does not match pattern [^[a-zA-Z0-9-.]++$]
````

After configuring a working `deviceIdPattern` to fix this, there is an error updating the credentials:
````
ClientErrorException: request body does not contain valid Credentials objects
````

**Comment by sophokles73** [comment]
> After configuring a working deviceIdPattern to fix this, there is an error updating the credentials:
`ClientErrorException: request body does not contain valid Credentials objects`

@calohmn 
If setting another pattern does not fix the problem, then why do you want to address this issue by means of setting another pattern?

**Comment by calohmn** [comment]
@sophokles73 Setting the pattern in the Hono chart is only the first part of the fix.
The 2nd part of the fix is using the fixed Hono chart in the cloud2edge package and adapting the "demo-device-credentials.json" file there (removing "device-id" entries which lead to the credentials parsing error).

**Comment by sophokles73** [comment]
Why would any of the device IDs cause any trouble after the pattern has been fixed to allow for the `:` character?

**Comment by calohmn** [comment]
@sophokles73 This second issue concerning the `request body does not contain valid Credentials objects` error has nothing to do with the device ID pattern check.
The "demo-device-credentials.json" contains "device-id" entries which aren't specified in the credentials schema. In Hono 1.2, these entries were ignored, in later versions these cause an error (`@JsonIgnoreProperties(ignoreUnknown = true)` was removed in `CommonCredential`).

**Comment by sophokles73** [comment]
Ah, now I see. Thanks @calohmn :+1:
