### ISSUE TITLE
Hono adapter pods and device registry pod can't be ready

### ISSUE THREAD

**Issue by vasanth-bk** [eclipse/packages#146]
I have newly deployed hono using latest helm chart (1.3.19) and latest hono app version (1.4.0) on a k8s cluster (1 master and 2 slaves). I have used Calico for CNI. The hono protocol adapters pods and device registry pod won't start even after 1 hour. 
Can anyone guide me how to fix it ?

![Hono-adapters-mqtt-pod-describe](https://user-images.githubusercontent.com/53044644/94235003-74b4c480-ff28-11ea-8806-f95847d53a69.png)
![kubectl-log-mqttpod-2](https://user-images.githubusercontent.com/53044644/94236326-ab8bda00-ff2a-11ea-9933-97bc478ce16a.png)
![kubectl-hono-status](https://user-images.githubusercontent.com/53044644/94234989-6ebee380-ff28-11ea-9cdd-cc568483735c.png)

**Comment by eliot4321** [comment]
Hi,

it seems the port "8088"  used it's wrong, I guess you should use 1883 or 31883 for the MQTT adapter if you are trying to access externally.

**Comment by vasanth-bk** [comment]
Hi @eliot4321, thanks for your reply.

I'm not trying to access the pods externally. Port 8088 is used for health check server as per the documentation, please see the values.yaml file [here](https://github.com/eclipse/packages/blob/master/charts/hono/values.yaml)

Please see the results of the pv and pvc command below
root@kubemaster:~# kubectl get pv -n hono
No resources found
root@kubemaster:~# kubectl get pvc -n hono
NAME                                   STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
eclipse-hono-prometheus-server         Pending                                                     4m23s
eclipse-hono-service-device-registry   Pending                                                     4m23s

**Comment by eliot4321** [comment]
Hi @vasanth-bk ,

which infrastructure you are using?
for the second  issue, as I predicted it seems you have no pv for your pvcs  you should check  the pvc  memory claim and create the pv in the same namespace.

**Comment by vasanth-bk** [comment]
Hi @eliot4321, 
Thanks, after configuring PV in the same namespace, the device registry pod has become 'ready' state.

I'm using 3 virtual machines from a GCP account. 1 master and 2 slaves, and I have used Calico for Container Network Interface. 

>   Liveness probe failed: Get "https://10.244.190.38:8088/liveness": dial tcp 10.244.190.38:8088: connect: connection refused
Readiness probe failed: Get "https://10.244.190.38:8088/readiness": dial tcp 10.244.190.38:8088: connect: connection refused


Could this issue be caused by Calico? But I read through their [documentation](https://docs.projectcalico.org/security/kubernetes-network-policy#create-ingress-policies) that states, by default they follow "Allow all" network policy.

I had retried the same installation using Flannel as the container network interface, still I'm facing the same issue. Do you have any other suggestion for a container/pod network interface other than Calico which is known to work well for hono ?

**Comment by vasanth-bk** [comment]
To add another point here, I have used the below values for health check server in values.yaml file. Is this right ?

      healthCheck:
        keyPath: "/etc/config/key.pem"
        certPath: "/etc/config/cert.pem"
        bindAddress: 127.0.0.1
        port: 8088

**Comment by sophokles73** [comment]
@vasanth-bk IMHO setting the *bindAddress* to `127.0.0.1` means that you can only access the port from the host that the service is running on. I think that this prevents k8s from accessing it and thus prevents your pods from entering the *ready* state. Can you try to set the bind address to `0.0.0.0` instead?

**Comment by vasanth-bk** [comment]
@sophokles73 thanks for the reply. Initially my setup was using `0.0.0.0` for the _bindAddress_ of health check server and I still faced the issue.

Anyway, I had deleted the host VMs from my GCP account and recreated the setup. This time the helm repo had 1.4.2 as the latest chart version, I had used the same chart with no modifications except setting `useLoadBalancer=false`. Now the pods are entering into ready state. Only thing I did differently was to create the PV required for device registry pod and prometheus pod before deploying the chart.

Now I seem to have hit another issue, that is one of the prometheus server pod is continuously restarting, could you please help me debug ? 

![kubectl-get-pods](https://user-images.githubusercontent.com/53044644/94905629-cfb36200-04ba-11eb-8849-29630b5b8740.png)
![kubectl-describe-prometheus](https://user-images.githubusercontent.com/53044644/94905621-cde99e80-04ba-11eb-86ff-49485475a6bc.png)
![kubectl-logs-prometheus](https://user-images.githubusercontent.com/53044644/94905894-35075300-04bb-11eb-92dc-f80e030c3922.png)

**Comment by sophokles73** [comment]
As the log indicates, it seems like Prometheus has no write access to the `/data` folder ...
Are you sure that the Prometheus pod's PVC has been successfully bound to a PV?
The full output of `kubectl describe pod` for the Prometheus pod would be helpful here as well as the output of the 
`kubectl get pv -n hono` and `kubrctl get pvc -n hono` commands ...

**Comment by vasanth-bk** [comment]
`/data` is a folder inside the container or on the node ?

Output of `kubectl get pv -n hono` and `kubrctl get pvc -n hono` commands :
```
root@kubemaster:~# k get pvc
NAME                                   STATUS   VOLUME               CAPACITY   ACCESS MODES   STORAGECLASS   AGE
eclipse-hono-prometheus-server         Bound    pv-prometheus        8Gi        RWO                           41m
eclipse-hono-service-device-registry   Bound    pv-device-registry   2Gi        RWO                           41m
root@kubemaster:~# k get pv
NAME                 CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                                       STORAGECLASS   REASON   AGE
pv-device-registry   2Gi        RWO            Retain           Bound    hono/eclipse-hono-service-device-registry                           42m
pv-prometheus        8Gi        RWO            Retain           Bound    hono/eclipse-hono-prometheus-server                                 42m
```

Full output of `kubectl describe pod` :

```
root@kubemaster:~# k describe pod eclipse-hono-prometheus-server-6dc58545bc-2td5r
Name:         eclipse-hono-prometheus-server-6dc58545bc-2td5r
Namespace:    hono
Priority:     0
Node:         kubeslave-1/10.148.0.10
Start Time:   Fri, 02 Oct 2020 08:43:19 +0000
Labels:       app=prometheus
              chart=prometheus-11.7.0
              component=server
              heritage=Helm
              pod-template-hash=6dc58545bc
              release=eclipse-hono
Annotations:  <none>
Status:       Running
IP:           10.244.1.14
IPs:
  IP:           10.244.1.14
Controlled By:  ReplicaSet/eclipse-hono-prometheus-server-6dc58545bc
Containers:
  prometheus-server-configmap-reload:
    Container ID:  docker://bdb1e9deb5c41c023aefa639fa5cab6cc95cb942db960092c5fdef03fa4d2592
    Image:         jimmidyson/configmap-reload:v0.3.0
    Image ID:      docker-pullable://jimmidyson/configmap-reload@sha256:d107c7a235c266273b1c3502a391fec374430e5625539403d0de797fa9c556a2
    Port:          <none>
    Host Port:     <none>
    Args:
      --volume-dir=/etc/config
      --webhook-url=http://127.0.0.1:9090/-/reload
    State:          Running
      Started:      Fri, 02 Oct 2020 08:43:25 +0000
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/config from config-volume (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from eclipse-hono-prometheus-server-token-tthst (ro)
  prometheus-server:
    Container ID:  docker://8f6bd8828f7f62a151267e69835f6a926e9b15999fadd310373a1c02845d8317
    Image:         prom/prometheus:v2.19.0
    Image ID:      docker-pullable://prom/prometheus@sha256:bfad037f95e5e34d595502aa02cac6467b7eadc4b08a601d150844003051fb1b
    Port:          9090/TCP
    Host Port:     0/TCP
    Args:
      --storage.tsdb.retention.time=15d
      --config.file=/etc/config/prometheus.yml
      --storage.tsdb.path=/data
      --web.console.libraries=/etc/prometheus/console_libraries
      --web.console.templates=/etc/prometheus/consoles
      --web.enable-lifecycle
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Fri, 02 Oct 2020 09:09:32 +0000
      Finished:     Fri, 02 Oct 2020 09:09:32 +0000
    Ready:          False
    Restart Count:  10
    Liveness:       http-get http://:9090/-/healthy delay=30s timeout=30s period=15s #success=1 #failure=3
    Readiness:      http-get http://:9090/-/ready delay=30s timeout=30s period=5s #success=1 #failure=3
    Environment:    <none>
    Mounts:
      /data from storage-volume (rw)
      /etc/config from config-volume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from eclipse-hono-prometheus-server-token-tthst (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             False
  ContainersReady   False
  PodScheduled      True
Volumes:
  config-volume:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      eclipse-hono-prometheus-config
    Optional:  false
  storage-volume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  eclipse-hono-prometheus-server
    ReadOnly:   false
  eclipse-hono-prometheus-server-token-tthst:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  eclipse-hono-prometheus-server-token-tthst
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                   From               Message
  ----     ------            ----                  ----               -------
  Warning  FailedScheduling  27m (x12 over 35m)    default-scheduler  0/2 nodes are available: 2 pod has unbound immediate PersistentVolumeClaims.
  Normal   Scheduled         27m                   default-scheduler  Successfully assigned hono/eclipse-hono-prometheus-server-6dc58545bc-2td5r to kubeslave-1
  Normal   Pulling           27m                   kubelet            Pulling image "jimmidyson/configmap-reload:v0.3.0"
  Normal   Pulled            27m                   kubelet            Successfully pulled image "jimmidyson/configmap-reload:v0.3.0" in 4.87984561s
  Normal   Created           27m                   kubelet            Created container prometheus-server-configmap-reload
  Normal   Started           27m                   kubelet            Started container prometheus-server-configmap-reload
  Normal   Pulling           27m                   kubelet            Pulling image "prom/prometheus:v2.19.0"
  Normal   Pulled            26m                   kubelet            Successfully pulled image "prom/prometheus:v2.19.0" in 7.811083015s
  Normal   Created           26m (x4 over 26m)     kubelet            Created container prometheus-server
  Normal   Pulled            26m (x3 over 26m)     kubelet            Container image "prom/prometheus:v2.19.0" already present on machine
  Normal   Started           26m (x4 over 26m)     kubelet            Started container prometheus-server
  Warning  BackOff           119s (x124 over 26m)  kubelet            Back-off restarting failed container
```

**Comment by sophokles73** [comment]
Ok, so the eclipse-hono-prometheus-server PVC seems to be bound successfully to the underlying pv-prometheus PV.
However, the Prometheus server pod is not able to write to the PV. That might be due to access restrictions on the PV's underlying folder in the node's filesystem ...

**Comment by vasanth-bk** [comment]
Ok, do I need to explicitly mention any access in the below yaml that I used for PV creation ?

```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prometheus
spec:
  accessModes: 
   - ReadWriteOnce
  capacity:
    storage: 8Gi
  hostPath:
    path: /tmp/data-prometheus
```

**Comment by sophokles73** [comment]
I don't think so but you will need to make sure that the `/tmp/data-prometheus` folder can be written to by the Prometheus pod ...

**Comment by sophokles73** [comment]
@vasanth-bk any news on this?

**Comment by vasanth-bk** [comment]
I tried troubleshooting and couple of suggestions from [here](https://github.com/aws/eks-charts/issues/21) and [here](https://github.com/prometheus/prometheus/issues/5976#issuecomment-532942295)

But those solutions didn't work for me, so I have installed hono without prometheus and grafana for the time being. So let me close this issue now.
