### ISSUE TITLE
Please check "Using specific Container Images" example in hono README.md

### ISSUE THREAD

**Issue by boaks** [eclipse/packages#151]
Thanks for adding the `honoContainerRegistry`. That makes it now very easy to use microk8s with a local registry.

I'm not sure, if the example using it, is well.

[Using specific Container Images](https://github.com/eclipse/packages/blob/master/charts/hono/README.md#using-specific-container-images)

```
helm install --dependency-update -n hono --set honoImagesTag=1.3.0-custom --set honoContainerRegistry=my-registry:9090 eclipse-hono eclipse-iot/hono
```

my felling is, using `honoContainerRegistry` and "eclipse-iot/" is one too much. I used 

```
helm install --dependency-update -n hono --set honoImagesTag=1.3.0-custom --set honoContainerRegistry=my-registry:9090 eclipse-hono hono
```

with success.

**Comment by sophokles73** [comment]
The `eclipse-iot/` prefix is necessary in order to tell helm in which *chart* repository the `hono` chart can be found. That is (usually) necessary because the Hono chart is not contained in the default Helm chart repository. It has nothing to do with the container registry nor the names of the container images.

**Comment by boaks** [comment]
Is that `eclipse-iot/` required, if I want to run `helm install` on "local charts"? 
Or must I remove it, if I want to use the local charts? 

(I clone this "packages" repository and execute the "helm install" from the charts folder of that. I assume, that uses local charts.)

**Comment by sophokles73** [comment]
If you want to install from a local folder then provide the path to the chart in the local file system instead

**Comment by boaks** [comment]
I understand. Thanks! That is then `hono` without `eclipse-iot/`.
