### ISSUE TITLE
Support using same Mongo DB instance

### ISSUE THREAD

**Issue by sophokles73** [eclipse/packages#152]
The c2e package should support having Ditto and Hono use the same Mongo DB instance. The chart should support either installing a single node Mongo DB instance or configuring an already existing DB instance which will then be used by Hono and/or Ditto.

**Comment by sophokles73** [comment]
The package actually already supports configuring Hono and Ditto to use an already existing Mongo DB instance. Hono can also be configured to use the instance started by Ditto when using the Mongo DB based registry. In fact, I wonder if we should make that the default setup, i.e. using the Mongo DB based registry and configure it to use Ditto's mongo instance.

WDYT? @ctron @thjaeckle @calohmn

**Comment by thjaeckle** [comment]
That makes a lot of sense to me - the MongoDB is already in the c2e package, so why not use it also for the Hono device registry ..

**Comment by sophokles73** [comment]
@calohmn @ctron any opinion?

**Comment by calohmn** [comment]
Yes, I think that should be the default setup.
