### ISSUE TITLE
Cannot mount secret into the Artemis container's filestystem

### ISSUE THREAD

**Issue by damian-gallo** [eclipse/packages#155]
According to the `values.yaml` file the mounted secrets should be specified at `hono.amqpMessagingNetworkExample.broker.artemis.extraSecretMounts` but only works when specified at `hono.amqpMessagingNetworkExample.broker.extraSecretMounts` (without "artemis").

It seems that the `artemis-deployment.yaml` is pointing at the wrong value:
`.Values.amqpMessagingNetworkExample.broker`
where it should be:
`.Values.amqpMessagingNetworkExample.broker.artemis`

**Comment by sophokles73** [comment]
@kaniyan Hi Karthees, is this something for you?

**Comment by kaniyan** [comment]
> @kaniyan Hi Karthees, is this something for you?

I will take a look at it.

**Comment by sophokles73** [comment]
Ok, thanks :+1:

**Comment by kaniyan** [comment]
@damian-gallo This issue has been fixed via PR #158 and this fix is there from version 1.4.5. Could you please take a look and close this issue?

**Comment by damian-gallo** [comment]
Thank you very much!
