### ISSUE TITLE
Problem with Kubernetes Service type configuration in Hono

### ISSUE THREAD

**Issue by LuLeRoemer** [eclipse/packages#171]
I think I found a problem in how Kubernetes Service types can be configured in Hono.
If I'm not mistaken, there are just two configuration options in how services are exposed: `LoadBalancer` and `NodePort`. However, if I would like to route traffic over a proxy, such as the [Ambassador API gateway](https://www.getambassador.io/products/api-gateway/), I usually use the `ClusterIP` type.
If I deploy my services using `NodePort` instead I would assume to unintentionally be able to access the service twice. Once via the port opened by `NodePort` and once via the port I configured in my API gateway/Ingress controller.
Therefore, I would propose to let the user set the Service type himself in the `values.yaml` instead of using the `useLoadBalancer` flag.

**Comment by sophokles73** [comment]
The *useLoadBalancer* flag has been the cause of arbitrary (configuration) problems and I tend to agree that we should deprecate its usage and instead let the user define the type of Hono's Services explicitly.
However, I guess that #411 should already address (fix?) the issue that you are experiencing.

@LuLeRoemer can this issue be closed?

**Comment by LuLeRoemer** [comment]
If I understand #411 correctly, it is about restricting setting the NodePort property if the user also set the useLoadBalancer property. In this issue, however, I just wanted to address that a user might want to define the `ClusterIP` service type manually when using an external gateway. In our specific use case, we were hosting Hono on a single node cluster, using the Ambassador API gateway (now called [Emissary-ingress](https://www.getambassador.io/docs/emissary)), to route traffic to Hono but also other backends running on the cluster.
However, as far as I understand, it is possible to define the service type since #301. Therefore, I will close this issue.
