### ISSUE TITLE
Add Eclipse IoT repository to artifacthub.io

### ISSUE THREAD

**Issue by sophokles73** [eclipse/packages#178]
We might want to think about having the Eclipse IoT chart repository being added to https://artifacthub.io in order to increase the reach of potential users.

https://github.com/artifacthub/hub/blob/master/docs/repositories.md

**Comment by ctron** [comment]
Did that a while ago: https://artifacthub.io/packages/search?page=1&org=eclipse-iot

**Comment by sophokles73** [comment]
Great :+1:  I tried to search for `eclipse-hono` but didn't succeed so I thought it wasn't integrated already.
