### ISSUE TITLE
Publishing Helm charts via packages project

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/packages#2]
Yesterday we had a discussion with a potentially new Ditto adopter @axdotl from kiwigrid on Gitter about changes to the Ditto Helm chart which he already contributed as PR.

We also discussed about the packaging and hosting of our Helm chart. The Ditto project doesn't host it yet, so kiwigrid did that, see: https://hub.helm.sh/charts/kiwigrid/ditto-digital-twins

I don't know whether e.g. Hono does host its Helm chart (packaged and available via a website and `index.yaml`), but I would like to host the "official" Helm charts of our projects by ourself so that improvements to the chart are added in a single place.

That's btw how kiwigrid's index.yaml looks like: https://kiwigrid.github.io/index.yaml

I think it would be a great idea to use the Eclipse IoT Packages project to distribute various Helm charts used in the packages, e.g. via the project site as a subfolder https://eclipse.org/packages/charts/ or via a github.io site of this repo (like kiwigrid does it).

That way we could simply document to add a Helm repo:
```
$ helm repo add eclipse-iot https://eclipse.org/packages/charts/
```

And afterwards all `eclipse-iot` charts could automatically be installed, e.g.:
```
$ helm install eclipse-iot/hono
$ helm install eclipse-iot/ditto
```

Or, for the packages:
```
$ helm install eclipse-iot/package-zero
```

Any ideas/comments on that?

**Comment by ctron** [comment]
I absolutely like that idea!

**Comment by thjaeckle** [comment]
What do you think about where to manage the Helm chart sources?

I see two options:
* Either copy the Helm sources from the project's GitHub repos to this repo and keep them manually in sync
* Have this repo contain the "only truth" for Eclipse IoT Packages Helm charts, delete the Helm chart sources from the project's Github repos

**Comment by axdotl** [comment]
I would prefer the 'single-point-of-truth' option. We would be glad, to support on this!

I suggest to do it in a similar way we do it for the kiwigrid/helm-charts. This means to have all charts in a single place (e.g. a chart-directory in `eclipse/packages/`), verify and package the charts with CircleCI and publish them via Github pages (maybe `eclipse.github.io`).
Afterwards add the created registry to Helm Hub: https://github.com/helm/hub to have the charts easy accessible for users.

**Comment by thjaeckle** [comment]
Using `eclipse.github.io/packages/` would work I think with the "GH pages" approach.
The OpenJ9 project also makes use of that already for their docs: https://eclipse.github.io/openj9-docs/

**Comment by monotek** [comment]
If there would be an official chart repo we could move our Hawkbit chart there too ;-)

https://github.com/kiwigrid/helm-charts/tree/master/charts/hawkbit-update-server

**Comment by ctron** [comment]
> Using `eclipse.github.io/packages/` would work I think with the "GH pages" approach.
> The OpenJ9 project also makes use of that already for their docs: https://eclipse.github.io/openj9-docs/

I think we should be able to publish this to the homepage. I would prefer `eclipse.org/packages/chart` over GitHub.

**Comment by thjaeckle** [comment]
> I think we should be able to publish this to the homepage. I would prefer `eclipse.org/packages/chart` over GitHub.

Agreed, that is also short enough :)

**Comment by axdotl** [comment]
Sounds good to me. How shall we proceed?

For the Chart pipeline we could take a lot of stuff from our existing pipeline (https://github.com/kiwigrid/helm-charts/tree/master/.circleci) (should I prepare a PR for this?)

As first chart we can either use [Hawkbit](https://github.com/kiwigrid/helm-charts/tree/master/charts/hawkbit-update-server) or [Ditto](https://github.com/eclipse/ditto/pull/553)

**Comment by thjaeckle** [comment]
FMPOV it wold be great to have you @axdotl, using Hono, Ditto and hawkBit, with your experience in Helm in board for contributions 👍 
The packages project uses as buildserver a Jenkins instance hosted by the Eclipse Foundation: https://ci.eclipse.org/packages

I think it is preferred to use the Eclipse Jenkins as well for the chart pipeline.
Do we agree on that, Packages team?

A quite new alternative would be GitHub actions which work really well from our first impressions of building PRs in the Ditto project.


Maybe - while starting the discussion about the Helm chart packaging - you could already contribute the hawkBit Helm chart?

A second point I would like to start discussing: Which folder structure to choose when we also want to distribute the Helm charts via this project?
I would suggest something like:

```
- charts
-- eclipse-ditto
-- eclipse-hawkbit
-- eclipse-hono
- homepage
- packages
-- package-zero
--- charts
--- templates
```

WDYT?

**Comment by axdotl** [comment]
I'll response in reverse order :)

I'm fine with the directory structure, but maybe we can omit the prefix `eclipse` for the helm charts, in my opinion this adds no value.

For Hawkbit chart I'd like to talk to @monotek upfront.

I would also give Github Actions a try (an action for [chart-testing](https://github.com/scottrigby/chart-testing-action) has arrived).
Package, publish and re-create repo index might become the tricky part (will also talk about this with @monotek ). 
Maybe we can arrange a call about this together with you (package team) to discuss the several options (jenkins, Github actions, other CI tooling)?

**Comment by thjaeckle** [comment]
Hm, I think the prefix `eclipse-` in the folder name will be useful if we also add other charts of dependencies, e.g. for Prometheus, Grafana, Logstash, ...
Then again, those would hopefully be already existing Helm charts which we can just "use".

**Comment by axdotl** [comment]
Got your point, but disagree ;)
There is no need to copy dependent chart here, as Helm itself has a [dependency mechanism](https://helm.sh/docs/topics/chart_best_practices/dependencies/#scrollpane) (all of the charts you mentioned are available from [Helm Hub](https://hub.helm.sh)).

**Comment by sophokles73** [comment]
Sorry for being late to the party ;-)

Here are my two cents:
1. I am also in favor of both maintaining the Eclipse IoT project and package charts in a single location (preferably in the pakages GitHub repository) as well as hosting them in an Eclipse (IoT) owned Helm chart repository.
2. I have no clear preference regarding whether the chart repo should be based on the Eclipse webserver we use for hosting the website or whether we should/could use GitHub pages. The former feels more *Eclipse*-ish but I think we should talk to Eclipse webmasters about storage space requirements etc. IIRC there used to be problems with disk capacity for the binary artifacts distributed from Eclipse servers in the past, so we should check.
3. I also think that we can omit the `eclipse-` prefix from the chart directories as we will only be hosting Eclipse (IoT) charts FMPOV.
4. Another question I would like to raise is: do we want to create our charts for Helm 2 or for Helm 3? I am not really sure whether that decision needs to be made at all since I do not know if a Helm 3 based chart can also be installed using Helm 2. Does anybody know or sure?

**Comment by sophokles73** [comment]
Another thing: I really like the way the [requirements for a chart](https://github.com/helm/charts/blob/master/CONTRIBUTING.md#how-to-contribute-a-chart) to be contributed to the `helm/charts` GitHub repo are defined. IMHO it would make sense to adopt these standards for this repository as well. That would also leave us the option to contribute our charts to `helm/charts` if we ever deem that desirable in the future ...

**Comment by sophokles73** [comment]
@axdotl 
> Maybe we can arrange a call about this together with you (package team) to discuss the several options (jenkins, Github actions, other CI tooling)?

I think that would be a great idea since I believe that this will be the most tricky part of the chart repository. Maybe we can also get inspiration from the way the build, test and deploy is done on `helm/charts`?

**Comment by monotek** [comment]
@sophokles73 
I would go for Github pages now as the way Helm charts are saved in a repo will change in the Helm 3.x future. In Helm 3.0 there is already alpha support for OCI (Dockerhub like) based repos, which will become the default in the future.

We also have some experience implementing a helm/charts like pipline in our helm repo (https://github.com/kiwigrid/helm-charts), based on circle ci. We can copy from that, if wanted. Its also no problem to adapt this on an own webserver.

Helm 2 charts are compatible to Helm 3. So no need to change something for now as Helm 2 will be supported for another year too.

**Comment by axdotl** [comment]
Could one of you (@thjaeckle or @sophokles73) take care of organizing a call? Because you know best who should attend.

**Comment by ctron** [comment]
Sorry for the delay … I have been a bit busy in the last few days.

I absolutely like the idea of setting up a call, I will create a new issue, so that we can find a good date to start with.

**Comment by ctron** [comment]
I've started working on the "develop" branch to publish charts to eclipse.org (or staging.eclipse.org).

**Comment by ctron** [comment]
Every chart which is now located in the `charts` folder, will be packages and deployed to the repository, which is available from https://eclipse.org/packages/charts

So I think we can close this issue.

**Comment by monotek** [comment]
The repository should be published on https://hub.helm.sh/ too.
I would do the pr but i'm not sure who to add to the maintainers section in: https://github.com/helm/hub/blob/master/repos.yaml

**Comment by axdotl** [comment]
I created a PR for adding repo to Helm Hub, see helm/hub/#227

**Comment by thjaeckle** [comment]
@axdotl I see that you chose the name "eclipse" for the `repos.yaml` on Helm Hub.
Wouldn't "eclipse-iot" be more specific? Someone could think that one is about the Eclipse IDE

**Comment by axdotl** [comment]
Thanks for the hint, I changed it.

**Comment by axdotl** [comment]
I guess this can be closed.

**Comment by thjaeckle** [comment]
I agree, thx @axdotl and @monotek for your great support regarding this topic 👍
