### ISSUE TITLE
Number of supported Kubernetes versions

### ISSUE THREAD

**Issue by sophokles73** [eclipse/packages#21]
I wonder if it is really necessary to check installation on basically *all* Kubernetes versions or if it would be sufficient to verify e.g. the three most recent versions only. I do not think that the vast majority of users will be interested in deploying to years old Kubernetes versions and it would also relieve us from the burden of maintaining compatibility forever ...

**Comment by sophokles73** [comment]
@ctron @calohmn @thjaeckle any thoughts?

**Comment by thjaeckle** [comment]
Public cloud providers like AWS (EKS) still support quite old versions, EKS currently: 
```
1.14.9
1.13.12
1.12.10
```
see: https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html

So IMHO 1.12 upwards is reasonable to check against.

**Comment by sophokles73** [comment]
Then that seems to be settled for the time being.
