### ISSUE TITLE
Install hawkbit helm chart with value.rabbitmq.volumePermissions.resources fails 

### ISSUE THREAD

**Issue by deschmih** [eclipse/packages#211]
Hi guys,

I'm using hawkbit helm chart version 1.3.1 with helm 3.5.2 . 
In my **value.yaml** file is a entry for **rabbitmq.volumePermissions.resources**
``` 
rabbitmq:
  enabled: true
  resources:
    limits: 
      cpu: 250m
      memory: 512Mi
    requests: 
      cpu: 250m
      memory: 512Mi
  volumePermissions:
    resources: 
      limits:
        cpu: 125m
        memory: 128Mi
      requests: 
        cpu: 125m
        memory: 128Mi
```
helm install fails with error:
```
Error: YAML parse error on hawkbit/charts/hawkbit/charts/rabbitmq/templates/statefulset.yaml: error converting YAML to JSON: yaml: line 39: mapping values are not allowed in this context helm.go:81: [debug] error converting YAML to JSON: yaml: line 39: mapping values are not allowed in this context
YAML parse error on hawkbit/charts/hawkbit/charts/rabbitmq/templates/statefulset.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
        /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests
        /home/circleci/helm.sh/helm/pkg/releaseutil/manifest_sorter.go:106
helm.sh/helm/v3/pkg/action.(*Configuration).renderResources
        /home/circleci/helm.sh/helm/pkg/action/action.go:165
helm.sh/helm/v3/pkg/action.(*Install).Run
        /home/circleci/helm.sh/helm/pkg/action/install.go:240
main.runInstall
        /home/circleci/helm.sh/helm/cmd/helm/install.go:242
main.newTemplateCmd.func2
        /home/circleci/helm.sh/helm/cmd/helm/template.go:73
github.com/spf13/cobra.(*Command).execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:850
github.com/spf13/cobra.(*Command).ExecuteC
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958
github.com/spf13/cobra.(*Command).Execute
        /go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
main.main
        /home/circleci/helm.sh/helm/cmd/helm/helm.go:80
runtime.main
        /usr/local/go/src/runtime/proc.go:204
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1374
```

helm template points out the problem:
<pre>
          securityContext:
            runAsUser: 0
          <b>resources:            limits: </b>
              cpu: 125m
              memory: 128Mi
            requests:
              cpu: 125m
              memory: 128Mi
          volumeMounts:
            - name: data
              mountPath: "/opt/bitnami/rabbitmq/var/lib/rabbitmq"
</pre>

The issue seems to be in line 73 in hawkbit\charts\rabbitmq\templates\statefulset.yaml
<pre>
      initContainers:
        - name: volume-permissions
          image: "{{ template "rabbitmq.volumePermissions.image" . }}"
          imagePullPolicy: {{ default "" .Values.volumePermissions.image.pullPolicy | quote }}
          command: ["/bin/chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.fsGroup }}", "{{ .Values.persistence.path }}"]
          securityContext:
            runAsUser: 0
          {{- if .Values.volumePermissions.resources }}
          <b>resources: {{- toYaml .Values.volumePermissions.resources | indent 12 }}</b>
          {{- end }}
          volumeMounts:
            - name: data
              mountPath: "{{ .Values.persistence.path }}"
</pre>

Changing content in line 73 from `resources: {{- toYaml .Values.volumePermissions.resources | indent 12 }}` to `resources: {{- toYaml .Values.volumePermissions.resources | nindent 12 }}` solves the problem.

**Comment by calohmn** [comment]
This issue in version 6.28.1 of the rabbitmq chart seems to have been [fixed](https://github.com/bitnami/charts/commit/43e70827ef73560e118907b3a2c0d7d9c72bce52#diff-43f6a9461c81b4dbbf596161ffc298893e558130cf09049a9dd68925e9bee488R72) in the following chart version 7.0.0.
I've created #218 to update the rabbitmq chart dependency in the hawkbit chart to a newer version.
