### ISSUE TITLE
Enable coap x509 support for hono

### ISSUE THREAD

**Issue by boaks** [eclipse/packages#223]
In order to enable coap to use x509, the `hono-adapter-coap-vertx-secret.yaml` must add

```sh
application.yml: |
    hono:
      coap:
        keyPath: /etc/hono/key.pem
        certPath: /etc/hono/cert.pem
```

**Comment by sophokles73** [comment]
@boaks Which kind of cipher suites do you want to enable this way? Adding the key and cert to the server will not (yet) allow a client to authenticate using an X.509 certificate as this functionality is not available in Hono 1.7.x.

**Comment by boaks** [comment]
I thought hono - master matches packages - master. 
If that is not the case, then this requested change will be required once hone gets release with that feature or when ever the master branches of hono and packages will be aligned according the features.

**Comment by sophokles73** [comment]
The master branch of *packages* contains charts that refer to particular versions of the projects. In case of Hono, this is currently version 1.7.1. You can determine the particular version from the `Chart.yml` file ...

**Comment by sophokles73** [comment]
@calohmn Based on this, I suggest to postpone #228 to after the Hono 1.8.0 release.

**Comment by calohmn** [comment]
Ok, yes.

**Comment by boaks** [comment]
It's sure OK to postpone that change.

> The master branch of packages contains charts that refer to particular versions of the projects.

For me this looks more like, that the packages are intended to work with a specific version. But experimentally someone may change the effective used version of hono  using `honoImagesTag`. That may then work or not. That a release refers to a release doesn't say something about the masters during development.
