### ISSUE TITLE
Kafka cluster bootstrap server configuration via Helm chart

### ISSUE THREAD

**Issue by prabhaone** [eclipse/packages#227]
We are trying to deploying hono with Kafka messaging component via helm chart.

we are running Kafka cluster and zookeeper separate cluster .

we are running Hono as separate kubernetes cluster.

As per the hono documentation we need to pass the bootstrap.servers as environment variable in the adminclient or common configuration.

How we can pass this environment variable via helm chart while deploying hono in the kubernetes cluster. Since i can't see the hono.kafka.adminClientConfig in the helm chart repository. Please suggest.

**Comment by sophokles73** [comment]
Support for configuring and using an external Kafka cluster has been added to the chart some time ago. Please refer to the README.md file for details.
