### ISSUE TITLE
[Hono] Make Device Registry with embedded DB the Default

### ISSUE THREAD

**Issue by b-abel** [eclipse/packages#249]
Hono 1.9.0 deprecates the file-based device registry implementation which is currently used as the default of the Hono chart. This could be replaced by the JDBC-based implementation with an embedded database, which is already supported with #235. 
Technically, this only requires changing the property "deviceRegistryExample.type" to "embedded" in the file `values.yaml`. 

The readme file should be updated as well. For instance, it states that the file-based implementation is used as the default. The part about the steps required to use a production-grade device registry should be updated. The part about the _Device Connection API_ should be checked as well if it contains assumptions about the default device registry which are no longer valid.

**Comment by sophokles73** [comment]
Sounds reasonable to me. Would you care to create a PR?

**Comment by b-abel** [comment]
> Sounds reasonable to me. Would you care to create a PR?

Sure. Will do.
