### ISSUE TITLE
make ditto-nginx init container image configurable

### ISSUE THREAD

**Issue by JeffreyThijs** [eclipse/packages#295]
Currently, the image of the nginx init container is hardcoded: 

https://github.com/eclipse/packages/blob/d94c358e02d82d42357865606395a9407ef7353b/charts/ditto/templates/nginx-deployment.yaml#L51

Therefore, make this configurable in order to allow pulling the image from another registry.

**Comment by thjaeckle** [comment]
@JeffreyThijs may I ask what your use case is for using a specific init container at this point? 
I'm just interested ..

**Comment by JeffreyThijs** [comment]
@thjaeckle, for deployments in environments which have no access to the internet it is required to pull the images from a private repository.
