### ISSUE TITLE
Install ditto problem

### ISSUE THREAD

**Issue by BaerSy** [eclipse/packages#30]
Tried to install ditto chart by following the instructions @ "https://github.com/eclipse/packages/tree/master/charts/ditto", can't complete the installation. The error messages are below:

**package-zero$ sudo helm repo add eclipse-iot https://eclipse.org/packages/charts**
"eclipse-iot" has been added to your repositories

**package-zero$ sudo helm repo update**
Hang tight while we grab the latest from your chart repositories...
...Skip local chart repository
...Successfully got an update from the "eclipse-iot" chart repository
...Successfully got an update from the "stable" chart repository
Update Complete. ⎈ Happy Helming!⎈ 

**package-zero$ sudo helm install eclipse-ditto eclipse-iot/ditto**
Error: This command needs 1 argument: chart name

I can't find "eclipse-iot/ditto" in the current folder. Where is it？

**Comment by thjaeckle** [comment]
Do you use Helm version 2?
Then please follow the Helm v2 docs: https://v2.helm.sh/docs/using_helm/#using-helm

For Helm v2 it should be:
```
helm install eclipse-iot/ditto --name eclipse-ditto
```

> I can't find "eclipse-iot/ditto" in the current folder. Where is it？

It is in the repo you added 2 lines above with `helm repo add eclipse-iot https://eclipse.org/packages/charts`

**Comment by BaerSy** [comment]
Yes, I am using Helm 2. Will try helm 3. 

Thanks
