### ISSUE TITLE
Drop k8s 1.18 early?!

### ISSUE THREAD

**Issue by ctron** [eclipse/packages#300]
I am currently facing the issue that we are using the Ingress resource for a bunch of charts of the new package. The situation with Ingress is, that "v1" got added in Kubernetes 1.19, and all previous versions get dropped in 1.22.

We are setting the minimum Kubernetes version in these charts to 1.19, so that works just fine.

However, the CI in this repository validates all chart, for all listed Kubernetes versions. And so the validation fails when testing with Kubernetes 1.18 (which is expected).

However, I don't seem to find any reasonable workaround for skipping a single chart for a single Kubernetes version.

Now there are two ways to "properly" deal with this. Implement support for `v1beta1` in these charts, and make them compatible with Kubernetes down to (IIRC) 1.16. Or add some elaborate "skip this version" mechanism in our CI.

Both options would mean some bigger task. I would tend to add Ingress `v1beta1` support, as I have no interest in maintaining a messy "skip version" script in the CI.

However, a simple alternative would be to just agree on dropping support for Kubernetes 1.18 when merging the new package. Kubernetes 1.23 is due early December this year. But it would be nice to merge the new package in the new weeks.

By the way: if any of you knows a magic "--skip-incompatible-version" switch, that would be awesome.

So @calohmn @sophokles73 @thjaeckle … what are your feelings on dropping Kubernetes 1.18 a bit early?

**Comment by sophokles73** [comment]
@ctron looks like the validation is no longer done against k8s 1.18. Can this issue be closed then?
