### ISSUE TITLE
Do not install Prometheus and Grafana by default

### ISSUE THREAD

**Issue by sophokles73** [eclipse/packages#316]
The Hono chart currently installs Prometheus and Grafana by default. However, my feeling is that most people do not really take advantage of it. Thus, I propose to not install it anymore by default. This would also reduce the minimum HW requirements for installing the (default) configuration ...

**Comment by kaniyan** [comment]
+1. I also prefer to keep the default installation slim.

**Comment by calohmn** [comment]
fine with me as well
