### ISSUE TITLE
[Hono] Remove configuration property hono.kafka.defaultClientIdPrefix

### ISSUE THREAD

**Issue by b-abel** [eclipse/packages#324]
The discussion in https://github.com/eclipse/hono/issues/2960 concluded that the configuration property `hono.kafka.defaultClientIdPrefix` is to be removed.

**Comment by calohmn** [comment]
I think we can remove it along with the update to Hono 1.11.0.
Removing it now would lead to client IDs with whitespace (e.g. "Hono AMQP Adapter-internal-cmd-d4378820-8425-4034-90d6-fa10a24a014e"), which is not ideal. For Hono 1.11.0 the format of the IDs shall be changed anyway.
