### ISSUE TITLE
one typo in "Hawkbit Installation page of Github"

### ISSUE THREAD

**Issue by BaerSy** [eclipse/packages#33]
There is a typo in the below second command line :  **relm ---helm**

helm repo add eclipse-iot https://eclipse.org/packages/charts
**relm** repo update
helm install eclipse-hawkbit eclipse-iot/hawkbit

**Comment by ctron** [comment]
Thanks for the issue. Could you create a PR?

**Comment by BaerSy** [comment]
Don't know how to create a PR :)
