### ISSUE TITLE
artemis failed to start

### ISSUE THREAD

**Issue by KeynesLee** [eclipse/packages#338]
artemis failed to start, errors as the enclosed figure.
It seems stuck at step **configure $instanceDir**

![image](https://user-images.githubusercontent.com/11400334/152768224-6b0a6cc2-0bec-4301-86fd-a7da5d8f6af0.png)

**Comment by KeynesLee** [comment]
I tried to add an additional Java opt   --no-autotune in startup script 
**/opt/apache-artemis/bin/launch.sh start** , then issues gone.

But I have no idea, what will this impacts ....

**Comment by sophokles73** [comment]
Hi @KeynesLee,

is this question related to the Eclipse Hono chart? If so, which version are you using and what platform are you trying to deploy to, e.g. minikube, Azure etc?

**Comment by KeynesLee** [comment]
Hi 

What we tried is use helm to install cloud2edge package.
https://www.eclipse.org/packages/packages/cloud2edge/installation/

The honor version installed by cloud2edge is 1.8.0 by default. Artemis in this version of hono is 2.13.0 

We  tried to  download  packages  ( git clone https://github.com/eclipse/packages.git ), revised packages/packages/cloud2edge/requirements.yaml to force it install newer hono (version: ~1.11.0 ) , update dependencies ( helm dependencies update ) then reinstall cloud2edge. Still no luck.

We tried to upgrade artemis-base image to version 2.16.0. We still get the same errors.

**Comment by sophokles73** [comment]
What container management platform are you trying to deploy to? BTW the Cloud2Edge chart has been updated to use the latest Eclipse Hono/Ditto versions ...

**Comment by KeynesLee** [comment]
Hi

We tried to install cloud2edge before the end of Jan, the version of Cloud2edge was 0.2.1 .
We followed the manual (https://www.eclipse.org/packages/packages/cloud2edge/installation/) to install cloud2edge on a Rancher RKE K8S cluster.

We may try the latest version (0.2.2 , released days ago) later.

**Comment by sophokles73** [comment]
> We may try the latest version (0.2.2 , released days ago) later.

That would be great. That said, I have to admit that I do not have much experience with deployment to Rancher apart from the Hono Sandbox deployment where we use a single node k3s installation.

So, my understanding is that you are able to install and run the package. The only issue that you see is that the Artemis broker is not able to do the auto tuning of the journal during startup, right? But apart from that, everything works as expected?
What hardware platform are you running the Rancher cluster on?

**Comment by KeynesLee** [comment]
#So, my understanding is that you are able to install and run the package. The only issue that you see is that the Artemis broker is not able to do the auto tuning of the journal during startup, right?  But apart from that, everything works as expected? <---**Yes!!**

The hardware we used to deploy Rancher RKE K8S cluster is 3 Dell PowerEdge R740 Server

**Comment by sophokles73** [comment]
> The hardware we used to deploy Rancher RKE K8S cluster is 3 Dell PowerEdge R740 Server

I was referring to the processor architecture, i.e. AMD64 or ARM etc. But I guess we are talking about AMD64 here ...

**Comment by KeynesLee** [comment]
Yes, it's AMD64.

**Comment by sophokles73** [comment]
Sorry, then I am running out of ideas. Maybe you can ask the Artemis community for reasons why the journal tuning wouldn't work?

**Comment by KeynesLee** [comment]
We tried  the latest 2 release : 0.2.2  and 0.2.3 we got the sames issue.
But we tried to deploy to and other K8S cluster, every thing was fine.

**Comment by sophokles73** [comment]
@KeynesLee can this be closed?

**Comment by KeynesLee** [comment]
We tried to deploy the same helm chart on another K8S cluster （also deployed by RKE）, and the issue was not appeared.
We cannot find out the root causes.

Close this issue for now.
