### ISSUE TITLE
[cloud2edge] documentation for MQTT message properties/payload

### ISSUE THREAD

**Issue by greg-mcnamara** [eclipse/packages#348]
Could anyone please point me to documentation about how to publish an MQTT message to Hono as part of a cloud2edge (+ditto) deployment? The docs here: https://www.eclipse.org/packages/packages/cloud2edge/tour/ provide examples for HTTP adapter but not MQTT. The Hono docs here: https://www.eclipse.org/hono/docs/user-guide/mqtt-adapter/ don't seem to be relevant to the hono-ditto deployment.

For example, in the cloud2edge docs, the HTTP publish telemetry call has a "topic" and a "path". I'm trying to use the topic as the MQTT topic, but where and how do I use the path? Should that be part of the payload, or another property of the message?

**Comment by thjaeckle** [comment]
The Ditto payload is exactly the same to send, regardless of the protocol adapter you send it to in Hono.
There is no relation of Mqtt topic and Ditto Protocol json topic. 

So just publish the same Ditto Protocol json message the example sends via Http to e.g. the `telemetry`topic of the Hono Mqtt adapter should do the trick.
