### ISSUE TITLE
Error: failed to download "package-zero" (hint: running `helm repo update` may help)

### ISSUE THREAD

**Issue by VolITSol** [eclipse/packages#35]
Hi,

I am new to this project and really interested in testing it. However - doing the "Getting started" /Install part..

Next, render the Helm charts:

mkdir output
helm template . --name package-zero --namespace package-zero --output-dir output

I always get this error:
PS C:\packages\packages\package-zero> helm template . package-zero --namespace package-zero --output-dir output
Error: failed to download "package-zero" (hint: running `helm repo update` may help)
Any Ideas?

Thanks a lot

**Comment by sophokles73** [comment]
@VolITSol 
firts of all, thanks for your interest in IoT Packages. We recently renamed *package-zero* (which was mostly a code name* to *Cloud2Edge*. We also have been very busy with setting up the infrastructure to also host the packages on the Helm chart repository. I will update the installation instructions today and I can tell you that it will become much, much easier to install the Cloud2Edge package. In fact, it will be as easy as installing one of the charts using the `helm` tool.
