### ISSUE TITLE
hono command router volume size in template is too small

### ISSUE THREAD

**Issue by KeynesLee** [eclipse/packages#361]
The template of   hono service command router volume PVC shall not fixed in 1 Mi.
(packages/charts/hono/templates/hono-service-command-router/hono-service-command-router-pvc.)
As not ALL the kinds of the storage support such a small size.

For example, the NetApp FAS storages could create volumes not smaller than 1Gi.

-----------------
spec:
  accessModes:
  - ReadWriteOnce
  {{- with .Values.commandRouterService.storageClass }}
  storageClassName: {{ . | quote }}
  {{- end }}
  resources:
    requests:
      storage: **1Mi**

**Comment by calohmn** [comment]
The above persistent volume is used if the Command Router is configured to use an embedded cache.
For production purposes, usage of a remote cache (data-grid) is recommended. In that case the persistent volume isn't used.

To enable usage of the data grid, either the `dataGridSpec` chart configuration must be set (configuring access to an existing Infinispan cluster) or the deployment of the example data grid must be enabled via `--set dataGridExample.enabled=true`.

**Comment by sophokles73** [comment]
Actually, the Command Router should not include a PVC anymore at all because the chart's example embedded cache configuration is no longer backed by a file since https://github.com/eclipse/packages/commit/308ac188b04713c2722a5518f17696b9e251c14c

@calohmn WDYT?

**Comment by calohmn** [comment]
@sophokles73 Good point. Yes, there is no reference in the config files any more to the `/var/lib/hono` location used in the mountPath of the persistent volume.

**Comment by sophokles73** [comment]
We might want to keep it for backwards compatibility but I'd rather not ...
