### ISSUE TITLE
DITTO_LOGGING_DISABLE_SYSOUT_LOG toggle switched

### ISSUE THREAD

**Issue by tobias-zeptio** [eclipse/packages#370]
In the helm chart for ditto there is an error where the condition and outcome is switched for each of the service deployments.

```
- name: DITTO_LOGGING_DISABLE_SYSOUT_LOG
  value: "{{ if .Values.global.logging.sysout.enabled }}true{{ else }}false{{ end }}"
```
It should be:

```
- name: DITTO_LOGGING_DISABLE_SYSOUT_LOG
  value: "{{ if .Values.global.logging.sysout.enabled }}false{{ else }}true{{ end }}"
```

**Comment by thjaeckle** [comment]
Oh, thanks. That's a really stupid bug.
Would you mind creating a PR?

**Comment by tobias-zeptio** [comment]
It's been a while, but here it is.
https://github.com/eclipse/packages/pull/371
