### ISSUE TITLE
Ditto / HawkBit: dependent charts cannot be resolved

### ISSUE THREAD

**Issue by calohmn** [eclipse/packages#372]
Bitnami has removed packages older than 6 months from their helm repo index - see https://github.com/bitnami/charts/issues/10539.

This means the `mongodb`, `mysql` and `rabbitmq` chart versions referenced as dependencies in the `ditto` and `hawkBit` charts cannot be found. The `hono` chart is not affected.

**Comment by carrodher** [comment]
Hi, please note all the previous Chart versions still exist and they are available as usual, please check [this post](https://github.com/bitnami/charts/issues/10539). This change only affects the `index.yaml` listing.

This change can potentially affect users or CI/CDs trying to package charts (`helm package` or `helm dep update`). **In any case regular installations or deployments**.

Apart from that, in the above-mentioned issue, you can see a workaround to continue using older versions as part of your Helm charts:

```console
$ helm repo add bitnami-pre-2022 https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
"bitnami-pre-2022" has been added to your repositories
```
or
```diff
-  repository: https://charts.bitnami.com/bitnami
+  repository: https://raw.githubusercontent.com/bitnami/charts/eb5f9a9513d987b519f0ecd732e7031241c50328/bitnami
```

Being said that, the recommendation is to use recent versions of the Helm charts in order to keep the deployments secure and up-to-date.

**Comment by stmaute** [comment]
@calohmn In order to get the Helm charts working we should switch to the new repository which you already did in #372.
I think we need to test the Ditto Chart with new MongoDB Chart version 4.4 and afterwards decided if we can do the update.

**Comment by stmaute** [comment]
@calohmn I have created a PR to update mongodb version for Ditto #374.

**Comment by stmaute** [comment]
@calohmn I have merged PR #374 so for Ditto we do not need to use this workaround.

**Comment by calohmn** [comment]
Reopening this, as there are now build errors in the Jenkins pipeline:
```
Building charts/hawkbit ...
+ dirname charts/hawkbit/Chart.yaml
+ /home/jenkins/agent/workspace/Website_master/helm package -u charts/hawkbit -d helm-repository
Error: no cached repository for helm-manager-91b1e65e9b2f631e58d61eb3d53eb80c2121816ad48f02d75a9bdb09bf9356b2 found. (try 'helm repo update'): open /home/jenkins/agent/workspace/Website_master/helm-cache/helm/repository/helm-manager-91b1e65e9b2f631e58d61eb3d53eb80c2121816ad48f02d75a9bdb09bf9356b2-index.yaml: no such file or directory
```
Strangely, the error doesn't occur on every pipeline run.

**Comment by calohmn** [comment]
An issue here could be that the rabbitmq chart `7.8.0` (used in the hawkBit chart) itself has the following `requirements.yaml`:
```
dependencies:
  - name: common
    version: 0.x.x
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
```
The current `https://charts.bitnami.com/bitnami` repository index doesn't have a `0.x.x` `common` chart any more, though.

That means the rabbitmq chart in hawkBit has to be updated to at least `8.0.0` - that version uses the `common` chart in version `1.x.x` which then can be found in the current bitnami index.

**Comment by calohmn** [comment]
The above mentioned Jenkins pipeline error (`Error: no cached repository [...]`) didn't occur again in the following 4 pipeline runs. Therefore closing this again.
