### ISSUE TITLE
NodePort Override

### ISSUE THREAD

**Issue by ReadyPJC** [eclipse/packages#409]
Hi all.

I am having some troubles in installing the Eclipse-Hono with helms.

The error is the following:
Error: INSTALLATION FAILED: Service "eclipse-hono-adapter-mqtt" is invalid: spec.ports[0].nodePort: Invalid value: 31883: provided port is already allocated

In my K3S cluster, I have a solution working that uses the MQTT and therefore the 31883 port.

Is it possible to change the ports of the NodePorts in the installation process? I didn't see anyhing related to that matter in the values.yaml file (https://github.com/eclipse/packages/blob/master/charts/hono/values.yaml).

Thanks.

**Comment by sophokles73** [comment]
What kind of kubernetes cluster are you deploying to when the error occurs?

**Comment by PJC-IONOS** [comment]
It is a K3S single node:

Client Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+k3s2", GitCommit:"fe3cecc219175ea85d7a95ed9e44349d94734bc7", GitTreeState:"clean", BuildDate:"2022-07-06T20:35:20Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.8+k3s2", GitCommit:"fe3cecc219175ea85d7a95ed9e44349d94734bc7", GitTreeState:"clean", BuildDate:"2022-07-06T20:35:20Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

I have a solution working in that cluster that uses a Mosquitto container and this one, uses the 31883 port. 

What I would like to do is to install Hono but with some changes regarding the ports.

Regards.

**Comment by sophokles73** [comment]
So, you are also running a Mosquitto container in this node and that Mosquitto container is already binding to port 31883, did I understand that correctly?

**Comment by PJC-IONOS** [comment]
Yes that's it. That's why I want to change the port of the NodePort by configuration.

**Comment by sophokles73** [comment]
No, the NodePort values are (currently) not configurable. However, if your k3s installation also supports LoadBalancer type services, then you may simply deploy Hono with setting the *useLoadBalancer* property to `false`. All externally accessible endpoints will then be exposed on ports that are dynamically determined by the load balancer implementation ...

**Comment by PJC-IONOS** [comment]
Ok. I will see the best solution for my case.

Thanks a lot!

We can close this issue.

**Comment by sophokles73** [comment]
I have checked the chart again and it seems that even with setting the *useLoadBalancer* property, the chart will still try to configure a node port for the MQTT adapter service. This seems to be a bug in the chart.

**Comment by PJC-IONOS** [comment]
Ok. I think it would be great in a new version, to have the possibility to choose the ports and/or to have random ones.

**Comment by sophokles73** [comment]
For the time being, I have created #411 which should allow you to use the LoadBalancer with Hono ...

**Comment by PJC-IONOS** [comment]
Great job. Thanks.

**Comment by sophokles73** [comment]
@ReadyPJC can this be closed?

**Comment by ReadyPJC** [comment]
Sorry for the late answer.

Yes we can close it.

Many thanks.

PJC

**Comment by sophokles73** [comment]
fixed via #411
