### ISSUE TITLE
Include new Ditto-UI to Ditto chart

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/packages#418]
Since Ditto 3.0.0, Ditto comes with an UI.
We could add this to the Ditto chart as well.

**Comment by bs3245** [comment]
Hi @thjaeckle,

I have deployed the cloud2edge package in an EC2 instance, but I couldn't able to reach the ditto explorer page using the ditto nginx IP. I have opened all the ports in my instances, but still got connection timed out.

But when I deployed the package in local vm I was able to view the ditto explorer using the ditto nginx IP and port. 

I want to know if there is any additional configuration required for bringing up the ditto explorer when deployed in cloud server. Could you please help me with this?

Thankx!

**Comment by thjaeckle** [comment]
@bs3245 sorry, I can't think about additional config.

So did you move to the Ditto hosted Helm chart, which includes the Ditto UI?

The deprecated chart maintained as part of the IoT Packages project will not receive the UI.
Therefore I am closing this as won't fix.

**Comment by bs3245** [comment]
@thjaeckle So does this mean I have make changes in the requirements.yaml file of cloud2edge package with ditto repository?

**Comment by calohmn** [comment]
@bs3245 There is already an issue (#486)  to update the cloud2edge chart with the latest ditto chart.

**Comment by bs3245** [comment]
@calohmn  So should I wait for the merge to happen or is there any other way to do this?

Thank you for the quick response.
