### ISSUE TITLE
Auto-provisioned device is not added in Ditto using C2E package

### ISSUE THREAD

**Issue by antoniyatrifonova** [eclipse/packages#427]
Using this guide [Cloud2Edge](https://www.eclipse.org/packages/packages/cloud2edge/tour/#create-a-new-connection-from-ditto-to-hono) when creating the connection between Ditto and Hono, with adding the additional setup **ImplicitThingCreation** mapper, the expected behavior is an automatic thing creation for a device via a gateway device. The actual result is that the auto-provisioned device is **not** added in Ditto as expected.

**Comment by antoniyatrifonova** [comment]
As described [here](https://www.eclipse.org/packages/packages/cloud2edge/tour/#create-a-new-connection-from-ditto-to-hono)  the used connection type should be **AMQP**. When the connection type is changed to **Kafka** this problem does not occur.

Please, update the [Cloud2Edge](https://www.eclipse.org/packages/packages/cloud2edge/tour/#create-a-new-connection-from-ditto-to-hono) guide, how to setup this package with Kafka.

**Comment by sophokles73** [comment]
@thjaeckle I do not understand the problem, maybe you can jump in?

**Comment by thjaeckle** [comment]
I think @kalinkostashki already knows about this - I am also not 100% sure.

**Comment by calohmn** [comment]
@antoniyatrifonova The cloud2edge tour has now been updated to document the creation of a new Kafka connection (see #493). As I've understood your comment above, this resolves the issue.
Please reopen if there is still an issue.
