### ISSUE TITLE
Extending cloud2edge chart for production use

### ISSUE THREAD

**Issue by devinsaini** [eclipse/packages#429]
This is a question.

I'm new to Helm Charts and designing a Hono and Ditto based IoT cloud. My question is should I use Cloud2Edge chart as a dependency and override/enable/disable components as needed or should I create a Helm Chart from scratch. If I'm building from scratch, should I also create sub-charts for Hono and Ditto instead of pulling them as dependencies like Cloud2Edge does.

I understand that Cloud2Edge isn't production ready as is, and we need to implement our own device registry and disable the example setups, and have our own Kafka and MongoDB clusters rather than the ones created by this Helm chart. But beyond this, is it advisable to use this chart, use its sub-charts only or do everything from scratch?

**Comment by kalinkostashki** [comment]
Hi,

From my point of view you can use both approaches.
I see it as follows:

1. Use Cloud2Edge

- already there for you and you can choose what you need like you already mentioned
- everything will be deployed in the same cluster
- quite a large dependency

2. Create your own chart on top of Hono and Ditto charts to replace cloud2edge or a directly one on top of that

- here the clear benefit is that you can do the things you want to of the already provided stuff
- bad thing is you have a a big dependency chain so your template manifest of the helm chart would be many thousands of lines big

3. Use Hono and Ditto charts only as separate charts and do separate charts for your device registry, kafka, mongodb, etc.

- added benefit is flexibility here and you don't have so much interdependence and you really know which chart does what
- may be a bit more work required(not too sure about this) 

P.S. You would also have to look at your CI/CD pipeline and how that would look like and use an approach best suited to that as well.

**Comment by devinsaini** [comment]
Thanks for the answer. It's a tough choice. 
I don't think I want to go with option 1 as I would like a clean chart without configs to disable Cloud2Edge example setup.  Nevertheless, Cloud2Edge will be a very good reference.
I will most likely use managed Kafka and MongoDB, and it makes the most sense to go with Option 2. Disabling Hono's example device registry is straightforward. I would like to have a single chart deployment for each environment.

I would also eventually want to add HawkBit to the mix. Is there any plan to add HawkBit to Cloud2Edge in the near future?

**Comment by sophokles73** [comment]
> I understand that Cloud2Edge isn't production ready as is, and we need to implement our own device registry and disable the example setups

You would only want to implement your own device registry if you already have a system of record for device data and you need/want to have Hono access the data in it. In that case you would want to create a service facade implementing the Tenant, Device Registration and Credentials APIs on top of it. But usually, you should be fine using e.g. the Mongo based registry that comes with Hono and configure it to use your (managed) Mongo DB instance ...

**Comment by sophokles73** [comment]
>  will most likely use managed Kafka and MongoDB, and it makes the most sense to go with Option 2. Disabling Hono's example device registry is straightforward.

I agree, you could use the c2e chart as a blueprint/starting point and strip everything you do not need.

**Comment by sophokles73** [comment]
> I would also eventually want to add HawkBit to the mix. Is there any plan to add HawkBit to Cloud2Edge in the near future?

No, there doesn't seem to be much support for this task from the hawkBit community. Maybe you can raise the issue there and/or even start working on integrating it with c2e yourself and contribute it?
Just adding the hawkBit chart to c2e shouldn't be too much of an issue. The more interesting question is to what level you expect integration to work? Is it just sharing device IDs between Hono's registry and hawkBit? IIRC there had been a PR for hawkBit some time (years?) ago that added a mechanism for polling Hono's registry for devices ...

**Comment by devinsaini** [comment]
Thanks for the replies. I was under the impression from the documentation that the example device registry isn't production ready. It'll definitely help since I don't already have a system of record for devices.
I noticed the Hawkbit PR open since 2019. I'll see if I can contribute hawkBit to c2e.

**Comment by sophokles73** [comment]
> I was under the impression from the documentation that the example device registry isn't production ready.

Would you mind providing a pointer to the (misleading) text in the documentation so that we can improve it?
The MongoDB registry is perfectly suitable for production. The main concern you need to take care of is setting up the Mongo DB in a fashion that suits your (production) needs. Using a managed service for that purpose seems like a wise choice :-)

**Comment by willtoth** [comment]
This document https://github.com/eclipse/packages/blob/master/charts/hono/README.md has the following quote

> The Helm chart by default deploys the example Device Registry that comes with Hono. The example registry provides implementations of the Tenant, Device Registration and Credentials APIs which can be used for example/demo purposes.

and further on

> In a production environment, though, usage of the example registry and messaging infrastructure is strongly discouraged and more sophisticated (custom) implementations of the service APIs should be used.

which clearly reads as saying the device registry is not production-worthy
