### ISSUE TITLE
Current Helm chart won't allow multiple Hono instances in the same K8s cluster

### ISSUE THREAD

**Issue by rbarberop** [eclipse/packages#431]
The current chart does not allow to deploy multiple instances of Hono in the same K8s cluster, separated in different namespaces.

```
kubectl create namespace hono-1
kubectl create namespace hono-2

helm install hono-1 eclipse-iot/hono -n hono-1 --wait
helm install hono-2 eclipse-iot/hono -n hono-2 --wait
```

The second install fails due to a collision in node ports.

Looks like all services have static node ports defined.

Would it be possible to remove the static node ports and let K8s select available ones?

**Comment by sophokles73** [comment]
Thanks for reporting. While your statement seems to be correct, may I ask in what kind of scenario you would want to deploy two Hono  instances to a cluster using NodePorts (instead of LoadBalancers)?

**Comment by sophokles73** [comment]
@rbarberop any info you want to share?

**Comment by rbarberop** [comment]
Sorry for the delay,

The idea of deploying multiple Hono instances in separate namespaces in the same K8s cluster is for demo purposes. 

I agree with you that the right way to do it would be using LoadBalancers, however the chart uses NodePorts:

https://github.com/eclipse/packages/blob/027509a2059e2abf892b1296e56f5c803af0940a/charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-svc.yaml#L29

https://github.com/eclipse/packages/blob/027509a2059e2abf892b1296e56f5c803af0940a/charts/hono/templates/hono-adapter-mqtt/hono-adapter-mqtt-svc.yaml#L35

**Comment by sophokles73** [comment]
Actually, the (current version of the) chart uses LoadBalancers by default, i.e. you would need to configure it explicitly to use NodePorts instead. So, if your cluster supports LoadBalancers, you should be good to go ...

**Comment by rbarberop** [comment]
I think I'm using the latest chart... and testing on GKE, so LoadBalancers are supported.

Running the following commands on a GKE cluster fails:

`kubectl create namespace hono-1
kubectl create namespace hono-2

helm install hono-1 eclipse-iot/hono -n hono-1 --wait
helm install hono-2 eclipse-iot/hono -n hono-2 --wait`

(to be more precise, deployment of hono-1 works... deployment of hono-2 fails:

`Error: INSTALLATION FAILED: Service "hono-2-kafka-0-external" is invalid: spec.ports[0].nodePort: Invalid value: 32094: provided port is already allocated`

**Comment by sophokles73** [comment]
Oh, I see. This comes from the kafka broker, not a Hono component. Can you try to install with
```sh
helm install hono-1 eclipse-iot/hono -n hono-1 --set kafka.externalAccess.service.nodePorts[0]= --wait --timeout 15m
```

**Comment by rbarberop** [comment]
I think the error is not only for Kafka (it was just the first one to appear in the race)...

I tried your suggestion, and when launching the helm install for the second instance of Hono, got this:

'Error: INSTALLATION FAILED: Service "hono-2-adapter-http" is invalid: spec.ports[0].nodePort: Invalid value: 30080: provided port is already allocated'

**Comment by sophokles73** [comment]
This should not happen unless you explicitly configure the chart to use NodePorts. Can you post the output of
```sh
helm search repo hono
```
and the command line you use for installing the chart?

**Comment by rbarberop** [comment]
As requested:

`helm search repo hono`

```
NAME                    CHART VERSION   APP VERSION     DESCRIPTION                                       
eclipse-iot/hono        2.1.5           2.1.1           Eclipse Hono™ provides remote service interface...
eclipse-iot/cloud2edge  0.4.0           0.4.0           Eclipse IoT Cloud2Edge (C2E) is an integrated s...
```

Commands to reproduce:

```
kubectl create namespace hono-1
kubectl create namespace hono-2
helm install hono-1 eclipse-iot/hono -n hono-1 --set kafka.externalAccess.service.nodePorts[0]=
helm install hono-2 eclipse-iot/hono -n hono-2 --set kafka.externalAccess.service.nodePorts[0]=
```

**Comment by sophokles73** [comment]
I have just now run your commands successfully towards a local minikube cluster.
Are you sure that you do not have any other services running that are using fixed NodePorts?
```sh
helm list --all-namespaces
```
should give you an idea of the releases that have been installed using Helm and
```sh
kubectl get service --all-namespace
```
should provide a list of all services and the ports they are bound to ...
