### ISSUE TITLE
C2E "Tour" documentation is outdated, still refers to AMQP 1.0 connections

### ISSUE THREAD

**Issue by thjaeckle** [eclipse/packages#432]
The current [Create a new connection from Ditto to Hono](https://www.eclipse.org/packages/packages/cloud2edge/tour/#create-a-new-connection-from-ditto-to-hono) still refers to creating a AMQP 1.0 connection to Hono.

AFAIK the c2e package however moved to Apache Kafka based connectivity from Ditto to Hono.
The tour documentation should be adjusted to reflect that change.

@kalinkostashki could you have a look please?

**Comment by kalinkostashki** [comment]
Yes, I will take a look and try to fix where appropriate :)

**Comment by ishwar25667** [comment]
Hi @thjaeckle ,
I am using c2e package & tried to establish connection with AMQP 1.0 but getting below issue.

{"status":504,"error":"connectivity:connection.failed","message":"Failed to consume sources: [command_response/my-tenant/replies-0, telemetry/my-tenant-0, event/my-tenant-0]","description":"command_response/my-tenant/replies-0: no such node [condition = amqp:not-found], telemetry/my-tenant-0: message address must not contain tenant ID only [condition = hono:bad-request], event/my-tenant-0: message address must not contain tenant ID only [condition = hono:bad-request]"}

{"status":504,"error":"connectivity:connection.failed","message":"Failed to consume sources: [telemetry/my-tenant/my-device-1-0, event/my-tenant/my-device-1-0]","description":"telemetry/my-tenant/my-device-1-0: no such node [condition = amqp:not-found], event/my-tenant/my-device-1-0: no such node [condition = amqp:not-found]"}

{
  "status": 504,
  "error": "connectivity:connection.failed",
  "message": "Failed to consume sources: [telemetry/org.acme/my-device-1/things/twin/commands/modify-0]",
  "description": "telemetry/org.acme/my-device-1/things/twin/commands/modify-0: can only publish for device of same tenant [condition = amqp:unauthorized-access]"
}

Using below documentation-

https://www.eclipse.org/packages/packages/cloud2edge/tour/#create-a-new-connection-from-ditto-to-hono

Can you please let me know how I can fix this issue?

**Comment by kalinkostashki** [comment]
Hi @ishwar25667 ,

I still haven't gotten around to fixing the documentation, but kafka is the default messaging used between Hono and Ditto for a long time. 
Are you using the default deployment of cloud2edge? If so there would be no AMQP messaging there.

**Comment by calohmn** [comment]
@kalinkostashki I've created #493 to update the cloud2edge tour.

**Comment by calohmn** [comment]
Fixed in #493.
