### ISSUE TITLE
c2e installation instructions are incorrect

### ISSUE THREAD

**Issue by sophokles73** [eclipse/packages#433]
The c2e package's [installation instructions](https://www.eclipse.org/packages/packages/cloud2edge/installation/) describe how to install the chart using either NodePorts or LoadBalancers for exposing Service endpoints.

When following the NodePort specific instructions, the c2e package will be installed with a mixture of using (actually requiring) LoadBalancers for Hono's Services but using NodePorts for Ditto's Services.

**Comment by sophokles73** [comment]
It might actually be easier to make the LoadBalancer based configuration the default in the c2e package because the Hono chart's default config also uses LoadBalancers but requires several properties to be set to use NodePorts instead whereas the Ditto chart only requires a single property to be set in order to use LoadBalancers ...

**Comment by calohmn** [comment]
@sophokles73 After having defined a consistent Hono/Ditto NodeType/LoadBalancer configuration in the cloud2edge chart `values.yaml`, it requires setting 3 "helm install" parameters (`hono.useLoadBalancer`, `hono.kafka.externalAccess.service.type`, `ditto.nginx.service.type`) to use the non-default configuration, irrespective of whether we use NodeType or LoadBalancer as default.

I would rather use the more basic NodeType configuration as default here (same as in Ditto).
I've created #504 for this.
