### ISSUE TITLE
Ditto version in Cloud2Edge 

### ISSUE THREAD

**Issue by OnurErtunc** [eclipse/packages#453]
It seems that Ditto version of Cloud2Edge package in eclipse-iot chart is updated to version 3.1.0+ but when I get the package with Helm, the current version of Ditto is 3.0.0.

**Comment by calohmn** [comment]
The issue here was, that the change towards using Ditto 3.1.0 in the cloud2edge chart didn't include an update of the cloud2edge chart version.

Since then, there have been new cloud2edge chart versions however. Currently Ditto version 3.3.6 is used there (cloud2edge version 0.5.0).
