### ISSUE TITLE
Only expose insecure ports in services if explicitly enabled

### ISSUE THREAD

**Issue by sophokles73** [eclipse/packages#457]
The k8s Services created for Hono's components currently always expose insecure ports, regardless of whether the insecure port has been enabled for the component.
The Dispatch Router of the example AMQP 1.0 based messaging infrastructure should support disabling the insecure external port by means of a configuration property.

**Comment by calohmn** [comment]
@sophokles73 Can this be closed?

**Comment by sophokles73** [comment]
Fixed via 506bdc6bfe8170e775e6d8f8b7aaec6488dff67e
