### ISSUE TITLE
Missing connections API endpoint into nginx-configmap.yaml

### ISSUE THREAD

**Issue by neottil** [eclipse/packages#466]
I've install ditto helm charts following this guide https://github.com/eclipse/packages/tree/master/charts/ditto.
When I call the connections API (/api/2/connections) with default basic auth devops:foobar I receive 401 response.

```
curl -v -u devops:foobar http://localhost:8080/api/2/connections
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
* Server auth using Basic with user 'devops'
> GET /api/2/connections HTTP/1.1
> Host: localhost:8080
> Authorization: Basic ZGV2b3BzOmZvb2Jhcg==
> User-Agent: curl/7.87.0
> Accept: */*
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 401 Unauthorized
< Server: nginx/1.23.3
< Date: Fri, 07 Apr 2023 14:53:35 GMT
< Content-Type: text/html; charset=utf-8
< Content-Length: 179
< Connection: keep-alive
* Authentication problem. Ignoring this.
< WWW-Authenticate: Basic realm="Authentication required"
< Access-Control-Allow-Methods: GET, POST, PUT, PATCH, DELETE, OPTIONS
< Access-Control-Allow-Credentials: true
< Access-Control-Expose-Headers: *
<
<html>
<head><title>401 Authorization Required</title></head>
<body>
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.23.3</center>
</body>
</html>
* Connection #0 to host localhost left intact
```

Looking the nginx-configmap.yaml file, the location /api/2/connections is missing. In the nginx.conf file under eclipse-ditto/ditto/deployment/kubernetes/deploymentFiles/nginx (https://github.com/eclipse-ditto/ditto/blob/master/deployment/kubernetes/deploymentFiles/nginx/nginx.conf) this configuration is present in line 31.

**Comment by thjaeckle** [comment]
Indeed that seems be missing from the chart.
We would appreciate a PR, as you already figured out what is missing and how to fix it.

**Comment by neottil** [comment]
I would be delighted to make this contribution. I tried to make a fix, but unfortunately I don't know nginx well and I'm not sure if this is the only problem.

**Comment by neottil** [comment]
Solved by pull request
