### ISSUE TITLE
Logo for cloud2edge package

### ISSUE THREAD

**Issue by eeeveee1** [eclipse/packages#47]
Here is a first idea for a logo of the cloud2edge package. Let me know what you think, so we can refine it.

![c2e_Logo_20200213](https://user-images.githubusercontent.com/56560642/74473706-58d24600-4ea4-11ea-867f-7744f9ee9e36.png)

**Comment by sophokles73** [comment]
@eeeveee1 this is awesome :+1: Thanks for doing this! 
Personally, I like option 1 better. I prefer the orange over the green and the *stricter* form of the number looks more *professional* to me.

**Comment by ctron** [comment]
Same here, same reasons. I do prefer the more round sides of 2) though … I think they give a more cloud-like appearance of the outline. But I guess making the outline of 1) more cloud-like in a future iteration isn't a problem :wink:

**Comment by dejanb** [comment]
Great work @eeeveee1. I also think the font of the option 1 works better for this type of the project. 

If I could add one more comment is that, for me the green color of option 2 is more effective (offers more contrast). So my ideal solution would be font from option 1 in color from option 2.

**Comment by sophokles73** [comment]
@thjaeckle @calohmn any opinion?

**Comment by thjaeckle** [comment]
I agree with @dejanb on this. Logo 1 with colors from 2.
But I'm not a color guy having a color deficiency. 😉

**Comment by calohmn** [comment]
I also agree with @dejanb, logo 1 with green instead of red color would be my favorite.

**Comment by eeeveee1** [comment]
Here is my second layout:

![c2e_Logo_20200311](https://user-images.githubusercontent.com/56560642/76454733-63b1c500-63d5-11ea-99fe-e15e4a6362fe.png)

**Comment by sophokles73** [comment]
@eeeveee1 looks great :-)

**Comment by dejanb** [comment]
We have a winner :)

**Comment by ctron** [comment]
Ok, so I will start putting in the new logo, once we have the ZIP file with the final files of the logo.

**Comment by eeeveee1** [comment]
here is the final version in different formats

cheers 

[c2e_Logo_fin.zip](https://github.com/eclipse/packages/files/4340165/c2e_Logo_fin.zip)
