### ISSUE TITLE
cloud2edge Command Router Certificates Expired after recreating the new certificates  

### ISSUE THREAD

**Issue by RameshKatkuri** [eclipse/packages#474]
I have seen this issue ( #472, #473 )tickets, which are closed by recreating the new certificate and released hono 2.4.2 version. But cloud2edge package dependency chats are not pointing to 2.4.2 version because of this facing certificate expired problem .

I have tried Hono installation separately which is pointing to 2.4.2 and working fine. 

Could you please help to resolve this issue

![version](https://github.com/eclipse/packages/assets/125072238/ea8239bf-4fde-44ce-af76-0f8b0966de72)

**Comment by sophokles73** [comment]
The fix should be quite easy to do: just replace 
```yaml
- name: hono
  version ^2.1.0
```

with
```yaml
- name: hono
   version: ^2.x
```

which should resolve to the most recent 2.x version of the Hono chart instead of the most recent 2.1.x version ...
We would be happy to receive a corresponding PR, @RameshKatkuri ?

**Comment by calohmn** [comment]
I think there is no change needed here.
```
- name: hono
  version ^2.1.0
```
This range (meaning `>=2.1.0` and `<3.0.0`) already includes the `2.4.2` version.

If you have checked out the iot-packages repository locally, you can go to the `packages/cloud2edge` directory and run
```
helm repo update && helm dependency update
```
to get the new version (see the content of the `charts` subdirectory).

**Comment by viscreoRyan** [comment]
I raised #472 and can confirm it has been resolved for me. The below is what I had to do to get the correct dependencies installed.

```bash
helm repo update
helm fetch eclipse-iot/cloud2edge --untar 
rm -r ./cloud2edge/charts 
cd cloud2edge 
helm dependency update
```
Then install from this directory 

There is probably a way better way to do this but I had issues with the helm dependency command.

**Comment by calohmn** [comment]
The issue here was, that we actually would have needed to create a new cloud2edge chart version after the hono chart update with the new certificates, so that the cloud2edge chart archive contains the new certificates.

But there have been several new cloud2edge chart versions now anyway - including the Hono chart with the new certificates.
When installing via `helm install [..] eclipse-iot/cloud2edge`, it just has to be ensured that `helm repo update` was run before.
