### ISSUE TITLE
HONO connecting to external KAFKA

### ISSUE THREAD

**Issue by paulocabrita-ionos** [eclipse/packages#477]
Hello everyone.

I'm trying to install HONO through `helm` and connect to an external kafka. Everything would run inside a K8S.

The KAFKA has a SSL configuration like the following:
- security.protocol=SSL
- ssl.truststore.type=PKCS12
- ssl.truststore.location=path_to_truststore
- ssl.truststore.password=password123

So, with that in mind, I try the following parameters for HONO:
- hono.kafkaMessagingClusterExample.enabled=false
- hono.adapters.kafkaMessagingSpec.commonClientConfig."bootstrap\.servers"=simple-kafka:9093
- hono.adapters.kafkaMessagingSpec.commonClientConfig."security\.protocol"=SSL
- hono.adapters.kafkaMessagingSpec.commonClientConfig."ssl\.truststore\.type"=PKCS12
- hono.adapters.kafkaMessagingSpec.commonClientConfig."ssl\.truststore\.location"=/tls/truststore.p12
- hono.adapters.kafkaMessagingSpec.commonClientConfig."ssl\.truststore\.password"=password123

Problems:
- HONO registry pod is saying me that it does not recognize the `ssl.*` parameters that I put. But, the parameters are compliant with the Apache Kafka Client configuration.

How can I connect to the external KAFKA?

I think it's related to this https://github.com/eclipse-hono/hono/issues/3457.

Help please.

Thanks

**Comment by sophokles73** [comment]
My understanding is that you are passing in the values using Helm's `--set` command line parameter, right?
Can you try to put all your config into a yaml file and use Helm's `-f` parameter to pull it in?

**Comment by paulocabrita-ionos** [comment]
@sophokles73 here goes part of the log of registry:
(I pointed to the lines with the misconfiguration information)

```
2023-07-14 10:19:46,075 INFO  [org.ecl.hon.dev.ser.DeviceRegistryHttpServer] (vert.x-eventloop-thread-1) vert.x uses native transport: true                                                     │
│ 2023-07-14 10:19:46,075 DEBUG [org.ecl.hon.dev.mon.con.MongoDbBasedHttpServiceConfigProperties] (vert.x-eventloop-thread-1) using key [/opt/hono/tls/tls.key] and certificate [/opt/hono/tls/tl │
│ 2023-07-14 10:19:46,081 INFO  [org.ecl.hon.dev.met.DeviceRegistryMetricsAdapter] (main) registering gauge [hono.tenants.total]                                                                  │
│ 2023-07-14 10:19:46,155 INFO  [org.ecl.hon.dev.ser.DeviceRegistryHttpServer] (vert.x-eventloop-thread-1) starting endpoint [name: v1/tenants, class: org.eclipse.hono.service.management.tenant │
│ 2023-07-14 10:19:46,156 INFO  [org.ecl.hon.dev.ser.DeviceRegistryHttpServer] (vert.x-eventloop-thread-1) starting endpoint [name: v1/devices, class: org.eclipse.hono.service.management.device │
│ 2023-07-14 10:19:46,156 INFO  [org.ecl.hon.dev.ser.DeviceRegistryHttpServer] (vert.x-eventloop-thread-1) starting endpoint [name: v1/credentials, class: org.eclipse.hono.service.management.cr │
│ 2023-07-14 10:19:46,163 INFO  [org.ecl.hon.dev.ser.DeviceRegistryAmqpServer] (vert.x-eventloop-thread-0) vert.x uses native transport: true                                                     │
│ 2023-07-14 10:19:46,164 DEBUG [org.ecl.hon.con.ServiceConfigProperties] (vert.x-eventloop-thread-0) using key [/opt/hono/tls/tls.key] and certificate [/opt/hono/tls/tls.crt] for identity      │
│ 2023-07-14 10:19:46,164 INFO  [org.ecl.hon.dev.ser.DeviceRegistryAmqpServer] (vert.x-eventloop-thread-0) starting endpoint [name: credentials, class: org.eclipse.hono.service.credentials.Dele │
│ 2023-07-14 10:19:46,164 INFO  [org.ecl.hon.dev.ser.cre.AbstractCredentialsService] (vert.x-eventloop-thread-0) Auto-provisioning of devices/gateways is available                               │
│ 2023-07-14 10:19:46,166 DEBUG [org.ecl.hon.ser.man.dev.DeviceAndGatewayAutoProvisioner] (vert.x-eventloop-thread-0) starting up                                                                 │
│ 2023-07-14 10:19:46,168 DEBUG [org.ecl.hon.dev.ser.DeviceRegistryHttpServer] (vert.x-eventloop-thread-1) OpenSSL [available: false, supports KeyManagerFactory: false]                          │
│ 2023-07-14 10:19:46,168 INFO  [org.ecl.hon.dev.ser.DeviceRegistryHttpServer] (vert.x-eventloop-thread-1) using JDK's default SSL engine                                                         │
│ 2023-07-14 10:19:46,169 INFO  [org.ecl.hon.dev.ser.DeviceRegistryHttpServer] (vert.x-eventloop-thread-1) enabling secure protocol [TLSv1.2]                                                     │
│ 2023-07-14 10:19:46,169 INFO  [org.ecl.hon.dev.ser.DeviceRegistryHttpServer] (vert.x-eventloop-thread-1) enabling secure protocol [TLSv1.3]                                                     │
| 2023-07-14 10:19:46,243 INFO  [org.ecl.hon.dev.ser.DeviceRegistryHttpServer] (vert.x-eventloop-thread-1) Service supports TLS ServerNameIndication: false                                       │
>>>>>> │ 2023-07-14 10:19:46,257 WARN  [org.apa.kaf.cli.pro.ProducerConfig] (vert.x-eventloop-thread-0) The configuration 'ssl.truststore.password' was supplied but isn't a known config.               │
>>>>>> │ 2023-07-14 10:19:46,257 WARN  [org.apa.kaf.cli.pro.ProducerConfig] (vert.x-eventloop-thread-0) The configuration 'ssl.truststore.type' was supplied but isn't a known config.                   │
│ 2023-07-14 10:19:46,345 DEBUG [org.ecl.hon.cli.kaf.met.MicrometerKafkaClientMetricsSupport] (vert.x-eventloop-thread-0) registered producer (2 producers total)                                 │
│ 2023-07-14 10:19:46,345 DEBUG [org.ecl.hon.cli.kaf.KafkaClientFactory] (vert.x-eventloop-thread-0) successfully created client [type: io.vertx.kafka.client.producer.impl.KafkaProducerImpl]    │
│ 2023-07-14 10:19:46,347 INFO  [org.ecl.hon.dev.ser.DeviceRegistryAmqpServer] (vert.x-eventloop-thread-0) starting endpoint [name: registration, class: org.eclipse.hono.service.registration.De │
│ 2023-07-14 10:19:46,349 DEBUG [org.ecl.hon.dev.ser.dev.EdgeDeviceAutoProvisioner] (vert.x-eventloop-thread-0) starting up                                                                       │
│ 2023-07-14 10:19:46,349 DEBUG [org.ecl.hon.cli.kaf.KafkaClientFactory] (vert.x-eventloop-thread-0) successfully created client [type: io.vertx.kafka.client.producer.impl.KafkaProducerImpl]    │
│ 2023-07-14 10:19:46,350 INFO  [org.ecl.hon.dev.ser.DeviceRegistryAmqpServer] (vert.x-eventloop-thread-0) starting endpoint [name: tenant, class: org.eclipse.hono.service.tenant.DelegatingTena │
│ 2023-07-14 10:19:46,362 INFO  [org.ecl.hon.dev.ser.DeviceRegistryAmqpServer] (vert.x-eventloop-thread-0) Server uses secure standard port 5671                                                  │
│ 2023-07-14 10:19:46,365 DEBUG [org.ecl.hon.dev.ser.DeviceRegistryAmqpServer] (vert.x-eventloop-thread-0) OpenSSL [available: false, supports KeyManagerFactory: false]                          │
│ 2023-07-14 10:19:46,365 INFO  [org.ecl.hon.dev.ser.DeviceRegistryAmqpServer] (vert.x-eventloop-thread-0) using JDK's default SSL engine                                                         │
│ 2023-07-14 10:19:46,365 INFO  [org.ecl.hon.dev.ser.DeviceRegistryAmqpServer] (vert.x-eventloop-thread-0) enabling secure protocol [TLSv1.2]                                                     │
│ 2023-07-14 10:19:46,366 INFO  [org.ecl.hon.dev.ser.DeviceRegistryAmqpServer] (vert.x-eventloop-thread-0) enabling secure protocol [TLSv1.3]                                                     │
│ 2023-07-14 10:19:46,366 INFO  [org.ecl.hon.dev.ser.DeviceRegistryAmqpServer] (vert.x-eventloop-thread-0) Service supports TLS ServerNameIndication: false                                       │
│ Terminating due to java.lang.OutOfMemoryError: Java heap space                                                                                                                                  │
│ Stream closed EOF for iotpipeline/c2e-service-device-registry-5bb77456fc-4vpwd (service-device-registry) 
```

**Comment by sophokles73** [comment]
There seem to have been issues with the Kafka client like this in the past where valid properties had been reported as unknown like in your case. It is unclear to me if this only meant that the properties were erroneously reported as unknown but had actually been used or if they also hadn't been used.

In your log file it looks like the registy pod crashes with an OOM exception. Are you sure that this is not your real problem?

**Comment by paulocabrita-ionos** [comment]
Some updates:
- the parameter `hono.adapters.kafkaMessagingSpec.commonClientConfig."ssl\.truststore\.location"=/xpto/tls_internal/truststore.p12` is detected by the registry pod. But it says that it can't find it which is normal because I didn't mounted when I deployed Hono. Can you point me to the right direction to pass the truststore file to Hono? So I'm curious to see if it's related to the ssl fields issue;
- when I install the Hono without the ssl parameters, I don't have the OOM exception.

**Comment by sophokles73** [comment]
Are you still passing in the properties using the `--set` command line arg?

You will need to (manually) create a k8s Secret for your Kafka credentials/truststore and configure all components that need access to Kafka to mount this secret. The Hono Helm chart's `values.yaml` file supports this by means of the

```yaml
   # extraVolumes contains additional kubernetes Volume definitions representing volumes
    # that can mounted into the container's file system.
    # The syntax is defined in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#volume-v1-core
    # This can be used to provide the container access to files contained in kubernetes
    # Secrets and/or ConfigMaps.
    extraVolumes: []

    # extraVolumeMounts describes how the additional volumes defined in "extraVolumes"
    # should be mounted into the container's file system.
    # The syntax is defined in https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.24/#volumemount-v1-core
    # A common use case for this is to mount a kubernetes Secret or ConfigMap into the
    # file system and then refer to the contained files in the component's configuration,
    # e.g. public and private keys or an application.yaml file.
    extraVolumeMounts: []
```

properties, which are defined for all components.

You will need to add corresponding volume definitions and mounts for your secret to all protocol adapters, the device registry and the command router component.

It will be a lot easier to set these properties by means of a yaml file in which you can make all of your customizations (including the Kafka properties) ...

**Comment by paulocabrita-ionos** [comment]
Thanks I will take a look ASAP. And yes, I'm using a yaml file to pass the arguments. :)

But meanwhile I'm having this issue: https://github.com/eclipse-hono/hono/issues/3513. Related to PVC.

**Comment by paulocabrita-ionos** [comment]
@sophokles73 I manage to come back to this issue. Using your input and a yaml file, the Hono is now connected to an external Kafka. I want to use Ditto with this kind of deployment so I'm guessing that now I have to create a connection between Kafka and Ditto so I will have everything integrated.

**Comment by sophokles73** [comment]
> I want to use Ditto with this kind of deployment so I'm guessing that now I have to create a connection between Kafka and Ditto so I will have everything integrated.

Yes, you will need to integrate Ditto with Hono which basically means that you need to create a new *Connection* in Ditto for your tenant. BTW the [Eclipse c2e IoT Package](https://www.eclipse.org/packages/packages/cloud2edge/) contains this setup out of the box for you to experiment with ...

**Comment by paulocabrita-ionos** [comment]
Closing this issue because what I'm facing is more Ditto related.
