### ISSUE TITLE
Create a Github actions Helm lint / install pipeline

### ISSUE THREAD

**Issue by monotek** [eclipse/packages#5]
As decided in the call we had (https://github.com/eclipse/packages/issues/4) we'll create a Github actions pipeline, which will lint (via https://github.com/helm/chart-testing) and install the Eclipse Helm charts.

We'll use Kubernetes Kind (https://github.com/kubernetes-sigs/kind) to install the charts in the last 3 recent Kubernetes versions.

Publishing the charts will be done in a later task. Likely this will be tracked in the following Ticket:
https://github.com/eclipse/packages/issues/2

**Comment by ctron** [comment]
I just saw that GitHub actions now also allows to hook up customer provided compute resources. Maybe that would be an alternative if we hit some kind of resource limitation.

**Comment by monotek** [comment]
We managed to switch our pipeline (https://github.com/kiwigrid/helm-charts) from Circle CI to Github actions now but still have to fix some workarounds, which had to be introduced. 

But i guess we should be ready to go some time next week :)

**Comment by monotek** [comment]
We moved from our own bash scripts to the official Helm Github actions but using some additions.

We've created some PRs for the actions which speed up ci a bit:
* https://github.com/helm/chart-testing-action/pull/11
* https://github.com/helm/kind-action/pull/6

Current state of the pipeline can be seen in this PR:
* https://github.com/kiwigrid/helm-charts/pull/252

So we're ready to use this. If the Github Actions PRs are not merged we're going to use our modified version or just stick with the original version, which would be just a bit slower.

**Comment by thjaeckle** [comment]
No, we don't have a deadline.

Great to see the progress you're making.

**Comment by monotek** [comment]
I've create a PR: https://github.com/eclipse/packages/pull/9

**Comment by monotek** [comment]
closed by: https://github.com/eclipse/packages/pull/9

**Comment by thjaeckle** [comment]
Verified by test PR #10
