### ISSUE TITLE
Update to latest Kafka chart in Hono chart

### ISSUE THREAD

**Issue by calohmn** [eclipse/packages#508]
The Kafka chart version 20.x currently used in the Hono chart contains many differences in terms of the chart configuration compared with the latest version (see Kafka chart [upgrading notes)](https://github.com/bitnami/charts/tree/main/bitnami/kafka#upgrading).

This makes it harder to find the corresponding chart configuration documentation when wanting to apply a custom Hono Kafka configuration.

Also the newest Kafka chart version contains better support for using KRaft (Kafka Without ZooKeeper).

**Comment by sophokles73** [comment]
@calohmn IMHO we can close this via #523, right?
