### ISSUE TITLE
Not fully initializing Pods(hono-adapter-amqp, hono-adapter-http, hono-service-command-router and hono-adapter-mqtt) In Cloud2edge

### ISSUE THREAD

**Issue by KATTA-00** [eclipse/packages#542]
After doing the [https://www.eclipse.org/packages/packages/cloud2edge/installation/](url) some pods are not correctly working!!!

![image](https://github.com/eclipse/packages/assets/83855665/531c5856-8ce6-4e7d-a362-12d33268de62)

________
e19129@instance-20240623-130751:~$ kubectl describe pod c2e-hono-adapter-amqp-845f59fdff-5qfwk -n opentwins
Name:             c2e-hono-adapter-amqp-845f59fdff-5qfwk
Namespace:        opentwins
Priority:         0
Service Account:  c2e-hono-adapter
Node:             opentwins/192.168.49.2
Start Time:       Sun, 23 Jun 2024 15:32:46 +0000
Labels:           app.kubernetes.io/component=adapter-amqp
                  app.kubernetes.io/instance=c2e
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=hono
                  app.kubernetes.io/version=2.5.1
                  helm.sh/chart=hono-2.6.1
                  pod-template-hash=845f59fdff
Annotations:      kubectl.kubernetes.io/default-container: adapter-amqp
                  prometheus.io/path: /prometheus
                  prometheus.io/port: 8088
                  prometheus.io/scheme: http
                  prometheus.io/scrape: true
Status:           Running
IP:               10.244.0.4
IPs:
  IP:           10.244.0.4
Controlled By:  ReplicaSet/c2e-hono-adapter-amqp-845f59fdff
Containers:
  adapter-amqp:
    Container ID:   docker://9456e6fb3fcc7415a3b83e51ca3c3f00cd79ee380c252fd6b05d738ef570369a
    Image:          index.docker.io/eclipse/hono-adapter-amqp:2.5.1
    Image ID:       docker-pullable://eclipse/hono-adapter-amqp@sha256:705337264f69c8de3d34bf30125d7a2511023891d3bea96e7324d546983a2359
    Ports:          8088/TCP, 5671/TCP, 5672/TCP
    Host Ports:     0/TCP, 0/TCP, 0/TCP
    State:          Running
      Started:      Sun, 23 Jun 2024 15:33:11 +0000
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     1
      memory:  512Mi
    Requests:
      cpu:      200m
      memory:   300Mi
    Liveness:   http-get http://:health/liveness delay=900s timeout=3s period=10s #success=1 #failure=3
    Readiness:  http-get http://:health/readiness delay=45s timeout=3s period=10s #success=1 #failure=3
    Environment:
      JDK_JAVA_OPTIONS:          -XX:MinRAMPercentage=80 -XX:MaxRAMPercentage=80
      KUBERNETES_NAMESPACE:      opentwins (v1:metadata.namespace)
      QUARKUS_CONFIG_LOCATIONS:  /opt/hono/default-logging-config/logging-quarkus-dev.yml
    Mounts:
      /opt/hono/config from adapter-amqp-conf (ro)
      /opt/hono/default-logging-config from default-logging-config (ro)
      /opt/hono/tls/ca.crt from tls-trust-store (ro,path="ca.crt")
      /opt/hono/tls/tls.crt from tls-keys (ro,path="tls.crt")
      /opt/hono/tls/tls.key from tls-keys (ro,path="tls.key")
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-2vxkk (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   True 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  tls-keys:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  c2e-hono-adapter-amqp-example-keys
    Optional:    false
  tls-trust-store:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      c2e-hono-example-trust-store
    Optional:  false
  default-logging-config:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      c2e-hono-default-logging-config
    Optional:  true
  adapter-amqp-conf:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  c2e-hono-adapter-amqp-conf
    Optional:    false
  kube-api-access-2vxkk:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason     Age                    From     Message
  ----     ------     ----                   ----     -------
  Warning  Unhealthy  4m1s (x4307 over 10h)  kubelet  Readiness probe failed: HTTP probe failed with statuscode: 503

__________

Caused by: java.security.cert.CertificateExpiredException: NotAfter: Sun Jun 23 09:06:00 UTC 2024
_______

**This was the outputs?? When logging it telling some certificate issue??**

**Comment by calohmn** [comment]
@KATTA-00 The example certificates in the Hono chart had expired (see #543). 
To address this, a new Hono chart version with new certificates has been created and there is now a new cloud2edge chart version referencing that Hono chart version (see #546).
You should ensure that you use the new cloud2edge chart version `0.9.1`.

**Comment by KATTA-00** [comment]
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready
ready.go:303: [debug] Deployment is not ready: opentwins/c2e-hono-adapter-amqp. 0 out of 1 expected pods are ready

Still, this pod is not initialling correctly.

**Comment by calohmn** [comment]
@KATTA-00 Could you run `helm search repo eclipse-iot` and `helm list -A` and verify that the output contains the cloud2edge chart version `0.9.1`?
If not, you should do a `helm repo update` and re-install the chart.
If you already had the newest chart version, then looking at the logs of the `c2e-hono-adapter-amqp` pod should give some insights.
