### ISSUE TITLE
hono certificate issues, kafka and other pods do not go into ready state.(but they are running except for kafka, none of them in ready state))  

### ISSUE THREAD

**Issue by icengiz** [eclipse/packages#545]
I am installing hono on minikube. Pods are not coming to ready state. I checked logs, it says SSL certificate issue. But kafa is not going into initiailized state, just keep restarting. What may the cause? If it is a certificate issue then how to refresh the certificates??

Thanks in advance.

**Comment by calohmn** [comment]
@icengiz The example certificates in the Hono chart had expired (see #543). 
To address this, a new Hono chart version has been created yesterday. Be sure to use Hono chart version `2.6.3`.
The cloud2edge chart is being updated in PR #546.
