### ISSUE TITLE
url for helm repo add

### ISSUE THREAD

**Issue by soheilade** [eclipse/packages#59]
Dear all, I am trying to add the iot packages repo to my helm. Could you please specify the helm command with the correct url?

**Comment by thjaeckle** [comment]
Hi. 
It seems we indeed have it not documented on the installation page. 

Until we fix that, this is the command you are looking for:
```
helm repo add eclipse-iot https://eclipse.org/packages/charts
helm repo update 
```

**Comment by soheilade** [comment]
thanks.

**Comment by thjaeckle** [comment]
Ah, the command indeed is on the website, in the [Pre-Requisites](https://www.eclipse.org/packages/prereqs/) section.
