### ISSUE TITLE
Choose and setup a more direct communication channel

### ISSUE THREAD

**Issue by ctron** [eclipse/packages#6]
I think it would make sense to set up a more direct communication channel. Something like Mattermost, Slack, Gitter, …

I know this is a difficult topic, and everyone has a personal favorite here. So let's start the discussion :grin:

**Comment by ctron** [comment]
The Eclipse Foundation hosts a Mattermost server: https://mattermost.eclipse.org … just that you know :wink:

**Comment by ctron** [comment]
We also have an empty gitter channel which we could use: https://gitter.im/eclipse/packages#

**Comment by sophokles73** [comment]
I am already using multiple chat systems including Gitter but excluding Mattermost so I would be in favor of not adding another one to my list and use Gitter.

**Comment by thjaeckle** [comment]
+1 for Gitter

**Comment by calohmn** [comment]
I would also vote for Gitter.

**Comment by stmaute** [comment]
+1 for Gitter

**Comment by laverman** [comment]
+1 for Gitter

**Comment by ctron** [comment]
So, let's use Gitter! -> https://gitter.im/eclipse/packages#
