### ISSUE TITLE
ditto services are pending forever due to insufficient memory

### ISSUE THREAD

**Issue by soheilade** [eclipse/packages#68]
Dear all, I tried to run the ditto helm chart but pods stays pending forever and when I describe, it says there is not enough memory, I used the command to limit resources to 2 G and 4 G but still same error. is there a minimum config requirement to have both hono and ditto in a k8s cluster?
Furthermore, I am following the instructions [here](https://www.eclipse.org/ditto/2018-05-02-connecting-ditto-hono.html#create-a-digital-twin) to create the digital twin, could you please elaborate to which pod https://ditto.eclipse.org/api/2/things refers to? gateway. enginx or something else?

**Comment by thjaeckle** [comment]
how many resources does your k8s pod(s) have?
The Ditto chart requests 6*256MiB, so at least 1,5GiB of memory. Add something for MongoDB and nginx and you should have at least 2GiB of memory available in your k8s pods.

Increasing the limit won't help, you could try to decrease the 256MiB "requests" to a lower value, but on your own risk that you might get out-of-memory errors during runtime then.

> Furthermore, I am following the instructions here to create the digital twin, could you please elaborate to which pod https://ditto.eclipse.org/api/2/things refers to? gateway. enginx or something else?
You need at least following Ditto's services to use the HTTP API: nginx, gateway, things, policies, concierge
search and connectivity are optional for the case you only want to use `/api/2/things`
