### ISSUE TITLE
submit data to hono

### ISSUE THREAD

**Issue by rainbowdn** [eclipse/packages#85]
Dear all, I am trying to publish some data to digital twin via this command  `curl -X POST -i -u MYTENANTID -H 'Content-Type: application/json' -d '{"temp": 14.51}' http://hono.eclipse.org:8080/telemetry` in here https://www.eclipse.org/ditto/2018-05-02-connecting-ditto-hono.html#test-the-integration , i am not using loadbalancer and my hono services are as follows: 
![image](https://user-images.githubusercontent.com/56249001/78133217-5610bd80-741e-11ea-92a3-29e93a56ac9e.png)

I tried replacing `hono.eclipse.org:8080` with the address of `eclipse-hono-adapter-http-vertx`   service which is  `nodeip : 30080` . i am receiving this message:
`Enter host password for user 'MYTENANTID':`
any idea what is this password?

**Comment by sophokles73** [comment]
Are you using the Cloud2Edge package?

**Comment by rainbowdn** [comment]
no, actually i used the helm charts of ditto and hono and i followed the guide in  https://www.eclipse.org/ditto/2018-05-02-connecting-ditto-hono.htm

**Comment by rainbowdn** [comment]
I used the script in cloud2Edge (https://www.eclipse.org/packages/packages/cloud2edge/scripts/setCloud2EdgeEnv.sh)  but still running this command 
`curl -i -u demo-device@org.eclipse.packages.c2e:demo-secret -H 'application/json' --data-binary '{
  "topic": "org.eclipse.packages.c2e/demo-device/things/twin/commands/modify",
  "headers": {},
  "path": "/features/temperature/properties/value",
  "value": 45
}' http://${HTTP_ADAPTER_IP}:${HTTP_ADAPTER_PORT_HTTP}/telemetry`
 leads to curl error cloud not resolve host which makes sense because my env variables are null as i am not using loadbalancer.

any idea?
Best regards
Soheila

**Comment by sophokles73** [comment]
That guide is almost two years old and (in many details) doesn't reflect the current versions of Hono and Ditto anymore. I would suggest you use the C2E package and take it from there ...

**Comment by thjaeckle** [comment]
I, as author of that blogpost, have to agree.
We will add a notice to that blogpost that it is outdated.
