### ISSUE TITLE
Connect Ditto to Hono for custom devices when using Cloud2Edge package

### ISSUE THREAD

**Issue by washboard** [eclipse/packages#97]
I've deployed a Cloud2Edge platform on minikube cluster following the guide at [https://www.eclipse.org/packages/packages/cloud2edge/installation/](url). It works well when testing with the build-in example device "org.eclipse.packages.c2e:demo-device", telemetry can be sent successfully and I can get the updated state from Ditto HTTP APIs, but when I have created a new custom device and try to send telemetry data to the hono HTTP adapter, I got "503 Service Unavailable" response repeatedly. I think it should be the problem that Ditto is not connected with Hono so there is no consumer to receive the telemetry.

I've done all the steps in the guide, including create a device in Hono and create a twin in Ditto, then I try to connect Ditto and Hono using the deprecated method at [https://www.eclipse.org/ditto/2018-05-02-connecting-ditto-hono.html](url), but failed to build the connection.

Could anyone help to give a detailed instruction about how to connect Ditto and Hono when I want to create a custom device?

Thanks in advance.

**Comment by thjaeckle** [comment]
Did you look at the cloud2edge "tour" documentation? 
https://www.eclipse.org/packages/packages/cloud2edge/tour/#create-the-digital-twin

**Comment by washboard** [comment]
Yes, I followed each steps in "Take a tour" webpage. Create another tenant, register a new device under that tenant, set device credentials, set policy, and create a twin at last. After all these done, I wish to publish telemetry to Hono, but got "503 Service Unavailable" response.
It seems that "creating another connection at Ditto" is not mentioned in "Take a tour" webpage, so I haven't done it. Should I refer to [https://www.eclipse.org/ditto/connectivity-manage-connections.html](url) to create connection to Hono?

**Comment by thjaeckle** [comment]
Will have a look tomorrow if I can quickly add creating a new Ditto connection to the tour.
You have to create one, yes.

Best use the template here (used in the packages setup) as basis:
https://github.com/eclipse/packages/blob/master/packages/cloud2edge/post-install/hono-connection.json

However you'll have to replace the placeholders correctly.

**Comment by washboard** [comment]
Thanks!

By the way, there is a typo in the command of "Setup a common policy" and "Create the twin" section. The parentheses don't match and there's a redundant '$' at the DITTO_API_PORT_HTTP position.

**Comment by ctron** [comment]
> By the way, there is a typo in the command of "Setup a common policy" and "Create the twin" section. The parentheses don't match and there's a redundant '$' at the DITTO_API_PORT_HTTP position.

A great chance for a first pull-request :grinning:

**Comment by thjaeckle** [comment]
Documentation was added and is live: https://www.eclipse.org/packages/packages/cloud2edge/tour/#create-a-new-connection-from-ditto-to-hono

**Comment by washboard** [comment]
Thanks for the quick update! Really helpful! Connection established and telemetry can be sent successfully.
